const input = document.querySelector('.input');
const output = document.querySelector('.output-res');
const list = document.querySelector('.list')
const showBtn = document.querySelector('.show')


showBtn.addEventListener('click', () => {
  showBtn.classList.contains('active') ?
    hiddenMenu() : showMenu()
})

let usd = 93;

const arr = [
  { "name": "7th Sector", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "A Boy and His Blob", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "A Fold Apart", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "A Musical Story", "price": "0.39", "region": "A", "data": "6/27", "status": "" },
  { "name": "ACE COMBAT™ 7: SKIES UNKNOWN", "price": "1.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "ADIOS Amigos", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "AEW: Fight Forever Elite Edition - Pre-Order", "price": "30.46", "region": "T", "data": "6/29", "status": "" },
  { "name": "ATOM RPG: Post-apocalyptic indie game", "price": "0.53", "region": "A", "data": "6/27", "status": "" },
  { "name": "Aaero: Complete Edition", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Achtung! Cthulhu Tactics", "price": "0.35", "region": "A", "data": "6/27", "status": "" },
  { "name": "Aery - Broken Memories", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Aery - Dreamscape", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Aery - Sky Castle", "price": "0.34", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Agent A: A puzzle in disguise", "price": "0.09", "region": "A", "data": "6/27", "status": "" },
  { "name": "Airborne Bundle", "price": "1.54", "region": "A", "data": "6/27", "status": "" },
  { "name": "Alchemist Simulator", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Alice Sisters", "price": "0.27", "region": "A", "data": "6/22", "status": "" },
  { "name": "Alone in the Dark", "price": "14.08", "region": "A", "data": "10/2", "status": "" },
  { "name": "Alone in the Dark - Digital Deluxe Edition", "price": "16.24", "region": "A", "data": "10/2", "status": "" },
  { "name": "Amazing Princess Sarah", "price": "0.69", "region": "T", "data": "6/27", "status": "" },
  { "name": "An Airport for Aliens Currently Run by Dogs", "price": "0.68", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ancestors: The Humankind Odyssey", "price": "1.81", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Angry Video Game Nerd I & II Deluxe", "price": "2.04", "region": "T", "data": "6/27", "status": "" },
  { "name": "Anima: Gate of Memories - Arcane Edition", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Animal Shelter Simulator", "price": "0.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Anno 1800™ Console Edition - Deluxe", "price": "17.65", "region": "A", "data": "6/27", "status": "" },
  { "name": "Antigraviator", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Aragami 2", "price": "0.67", "region": "A", "data": "6/27", "status": "" },
  { "name": "Aragami: Shadow Edition", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Arcade Classics Anniversary Collection", "price": "1.03", "region": "T", "data": "6/27", "status": "" },
  { "name": "Arcade Spirits: The New Challengers", "price": "0.85", "region": "A", "data": "6/27", "status": "" },
  { "name": "Arcadegeddon", "price": "2.73", "region": "T", "data": "6/27", "status": "" },
  { "name": "Archaica: The Path Of Light", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Area 86", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Arietta of Spirits", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Odyssey", "price": "1.84", "region": "A", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Odyssey - GOLD EDITION", "price": "3.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Origins", "price": "1.38", "region": "A", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Syndicate Gold Edition", "price": "2.22", "region": "T", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Valhalla Complete Edition", "price": "12.03", "region": "A", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Valhalla Deluxe Edition", "price": "5.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Assassin's Creed® Valhalla Ragnarök Edition", "price": "7.61", "region": "T", "data": "6/27", "status": "" },
  { "name": "Assault Android Cactus", "price": "0.15", "region": "A", "data": "6/27", "status": "" },
  { "name": "Asterigos: Curse of the Stars", "price": "2.71", "region": "T", "data": "6/27", "status": "" },
  { "name": "Atomicrops", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Awarded Platformer Bundle", "price": "0.66", "region": "A", "data": "12/3", "status": "" },
  { "name": "Axis Football 2023", "price": "7.31", "region": "C", "data": "6/27", "status": "" },
  { "name": "Ayre and the Crystal Comet", "price": "4.68", "region": "I", "data": "6/27", "status": "" },
  { "name": "BROKEN MIND", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Backbone", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bad North: Jotunn Edition", "price": "0.18", "region": "A", "data": "6/27", "status": "" },
  { "name": "Banner Saga 3", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Barn Finders", "price": "4.09", "region": "T", "data": "6/27", "status": "" },
  { "name": "Barn Finders and Treasure Hunter Simulator Bundle", "price": "1.03", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bassmaster® Fishing 2022: Super Deluxe Edition", "price": "1.76", "region": "T", "data": "6/27", "status": "" },
  { "name": "Battle Kid: Fortress of Peril", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Big Rumble Boxing: Creed Champions", "price": "5.74", "region": "E", "data": "6/27", "status": "" },
  { "name": "BioShock 2 Remastered", "price": "1.21", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "BioShock Infinite: The Complete Edition", "price": "1.93", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "BioShock Remastered", "price": "1.93", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Biped", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bite the Bullet", "price": "0.17", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Blair Witch", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Blazing Chrome", "price": "0.39", "region": "A", "data": "6/27", "status": "" },
  { "name": "Blind Fate: Edo no Yami", "price": "0.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "BloodRayne: ReVamped", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bloons TD 5", "price": "0.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "Blow & Fly", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bomber Crew", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bomber Crew Deluxe Edition", "price": "0.96", "region": "A", "data": "6/27", "status": "" },
  { "name": "Boomerang Fu", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bot Gaiden", "price": "7.02", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Brave Soldier - Invasion of Cyborgs", "price": "2.62", "region": "I", "data": "6/29", "status": "" },
  { "name": "Bridge Constructor Bundle", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bridge Constructor Portal", "price": "0.12", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bridge Constructor Stunts", "price": "0.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bridge Constructor: The Walking Dead", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Broken Sword 5 - the Serpent’s Curse", "price": "0.10", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bumblebee - Little Bee Adventure", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Bus Simulator 21", "price": "8.04", "region": "E", "data": "6/27", "status": "" },
  { "name": "Bus Simulator 21 Next Stop - Gold Edition", "price": "10.08", "region": "E", "data": "6/27", "status": "" },
  { "name": "Butterfly", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Butterfly 2", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "CODE VEIN", "price": "1.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "CONTRA: ROGUE CORPS", "price": "0.93", "region": "T", "data": "6/27", "status": "" },
  { "name": "Calico", "price": "0.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "Call of Duty®: Modern Warfare® II - Cross-Gen Bundle", "price": "15.42", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Can't Drive This", "price": "0.74", "region": "A", "data": "6/27", "status": "" },
  { "name": "Carnivores: Dinosaur Hunt", "price": "0.64", "region": "A", "data": "6/27", "status": "" },
  { "name": "Castlevania Advance Collection", "price": "3.70", "region": "T", "data": "6/27", "status": "" },
  { "name": "Castlevania Anniversary Collection", "price": "1.03", "region": "T", "data": "6/27", "status": "" },
  { "name": "Cat Quest II", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cat Souls", "price": "0.22", "region": "A", "data": "6/24", "status": "" },
  { "name": "Catlateral Damage: Remeowstered", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Chasm", "price": "0.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "Chernobylite", "price": "5.60", "region": "T", "data": "6/27", "status": "" },
  { "name": "Chess Gambit", "price": "0.46", "region": "A", "data": "6/24", "status": "" },
  { "name": "Chess Ultra", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Child of Light® Ultimate Edition", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Children of Morta: Complete Edition", "price": "0.51", "region": "A", "data": "6/27", "status": "" },
  { "name": "Chivalry 2 King's Edition", "price": "1.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "ChromaGun", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cities: Skylines - Premium Edition 2", "price": "1.00", "region": "A", "data": "6/27", "status": "" },
  { "name": "Clunky Hero", "price": "1.26", "region": "T", "data": "6/27", "status": "" },
  { "name": "Codex of Victory", "price": "0.56", "region": "A", "data": "6/27", "status": "" },
  { "name": "Conan Exiles", "price": "16.47", "region": "J", "data": "6/27", "status": "" },
  { "name": "Conan Exiles", "price": "1.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Conan Exiles - Complete Edition October 2021", "price": "6.92", "region": "A", "data": "6/27", "status": "" },
  { "name": "Conan Exiles - Isle of Siptah Edition", "price": "26.75", "region": "J", "data": "6/27", "status": "" },
  { "name": "Conan Exiles - Isle of Siptah Edition", "price": "1.98", "region": "A", "data": "6/27", "status": "" },
  { "name": "Conan Exiles – Complete Edition", "price": "78.91", "region": "M", "data": "6/27", "status": "" },
  { "name": "Construction Simulator", "price": "10.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "Construction Simulator - Extended Edition", "price": "11.89", "region": "E", "data": "6/27", "status": "" },
  { "name": "Construction Simulator 2 US - Console Edition", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Construction Simulator 3 - Console Edition", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Contra Anniversary Collection", "price": "0.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cook, Serve, Delicious! 2!!", "price": "0.19", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cook, Serve, Delicious! 2/3 Bundle!!", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cook, Serve, Delicious! 3?!", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Crashbots", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Crazy Athletics - Summer Sports and Games", "price": "0.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Creaks", "price": "1.00", "region": "A", "data": "6/27", "status": "" },
  { "name": "Creepy Tale", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Crime Boss: Rockay City", "price": "7.07", "region": "T", "data": "6/30", "status": "" },
  { "name": "Crysis Remastered Trilogy", "price": "6.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cyber Complex", "price": "0.10", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cyberpunk 2077", "price": "8.02", "region": "A", "data": "6/27", "status": "" },
  { "name": "Cyberpunk 2077 & Phantom Liberty Bundle", "price": "31.06", "region": "T", "data": "6/27", "status": "" },
  { "name": "Cymatically Muffed", "price": "0.55", "region": "T", "data": "6/27", "status": "" },
  { "name": "DARK SOULS™ II: Scholar of the First Sin", "price": "11.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "DARK SOULS™ III", "price": "17.25", "region": "A", "data": "6/27", "status": "" },
  { "name": "DARK SOULS™ III - Deluxe Edition", "price": "24.47", "region": "A", "data": "6/27", "status": "" },
  { "name": "DARK SOULS™: REMASTERED", "price": "11.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "DARKLAND 3", "price": "0.06", "region": "A", "data": "6/24", "status": "" },
  { "name": "DEMON'S TILT", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "DOOM Eternal: Year One Pass", "price": "2.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "DOOM Eternal: Year One Pass (PC)", "price": "2.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "DRAGON BALL FIGHTERZ", "price": "1.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "DRAGON BALL XENOVERSE", "price": "0.48", "region": "A", "data": "6/27", "status": "" },
  { "name": "DRAGON BALL Z: KAKAROT", "price": "7.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "DUCATI - 90th Anniversary", "price": "0.15", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dark Nights with Poe and Munro", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dawn of Man", "price": "0.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dawn of Man + Planetbase", "price": "1.03", "region": "A", "data": "6/27", "status": "" },
  { "name": "DayZ", "price": "1.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "DayZ Livonia Edition", "price": "2.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dead Ground", "price": "0.22", "region": "A", "data": "6/23", "status": "" },
  { "name": "Death Road to Canada", "price": "0.18", "region": "A", "data": "6/27", "status": "" },
  { "name": "Deep Diving Adventures", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Deiland: Pocket Planet", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Demoniaca: Everlasting Night", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dimension Drive", "price": "0.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dishonored®: Death of the Outsider™ Deluxe Bundle", "price": "2.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Disintegration", "price": "2.50", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Don't Starve Mega Pack 2020", "price": "0.93", "region": "A", "data": "6/22", "status": "" },
  { "name": "Don't Starve Together: Console Edition", "price": "0.21", "region": "A", "data": "6/22", "status": "" },
  { "name": "Don't Starve: Giant Edition", "price": "0.15", "region": "A", "data": "6/22", "status": "" },
  { "name": "Don't Starve: Giant Edition + Shipwrecked Expansion", "price": "0.19", "region": "A", "data": "6/22", "status": "" },
  { "name": "Door Kickers: Action Squad", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dou", "price": "0.06", "region": "A", "data": "6/28", "status": "" },
  { "name": "Dragon's Lair Trilogy", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dread Nautical", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "Driven Out", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Drone Gladiator", "price": "0.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dwarrows", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Dying Light: Definitive Edition", "price": "2.10", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "EA SPORTS™ FIFA 23 Standard Edition Xbox One", "price": "7.40", "region": "T", "data": "7/4/", "status": "" },
  { "name": "EA SPORTS™ FIFA 23 Standard Edition Xbox One", "price": "8.88", "region": "T", "data": "12/3", "status": "" },
  { "name": "EA SPORTS™ FIFA 23 Standard Edition Xbox Series X|S", "price": "8.46", "region": "T", "data": "7/4/", "status": "" },
  { "name": "EA SPORTS™ FIFA 23 Ultimate Edition Xbox One & Xbox Series X|S", "price": "16.92", "region": "T", "data": "7/4/", "status": "" },
  { "name": "EVERSPACE™", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Eagle Island Twist", "price": "1.77", "region": "T", "data": "6/27", "status": "" },
  { "name": "Effie", "price": "0.34", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Embr", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Empire of Angels IV", "price": "0.46", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Escape Dead Island", "price": "0.16", "region": "A", "data": "12/3", "status": "" },
  { "name": "Esports Life Tycoon", "price": "0.68", "region": "A", "data": "6/27", "status": "" },
  { "name": "FLASHOUT 3", "price": "8.87", "region": "A", "data": "6/27", "status": "" },
  { "name": "FROGUN", "price": "0.56", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Fantasy Dash", "price": "0.06", "region": "A", "data": "6/27", "status": "" },
  { "name": "Far Cry® 3 Classic Edition", "price": "0.45", "region": "A", "data": "6/27", "status": "" },
  { "name": "Far Cry® 4", "price": "0.54", "region": "A", "data": "6/27", "status": "" },
  { "name": "Far Cry® 5", "price": "1.38", "region": "A", "data": "6/27", "status": "" },
  { "name": "Far Cry® 6", "price": "5.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Far Cry® 6 Game of the Year Edition", "price": "12.03", "region": "A", "data": "6/27", "status": "" },
  { "name": "Far Cry® New Dawn", "price": "1.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Farm Manager 2022", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Farm Together", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Figment: Journey Into the Mind", "price": "1.36", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Firefighting Simulator - The Squad", "price": "6.86", "region": "E", "data": "6/27", "status": "" },
  { "name": "Firewatch", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Fishing Adventure", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Fishing: Barents Sea Complete Edition", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Fishing: North Atlantic", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Fishing: North Atlantic Enhanced Edition", "price": "1.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Formula Bit Racing DX", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Fortified", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Fran Bow", "price": "3.82", "region": "T", "data": "6/27", "status": "" },
  { "name": "Frostpunk: Complete Collection", "price": "0.77", "region": "A", "data": "6/27", "status": "" },
  { "name": "Furi", "price": "0.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "GRIDD: Retroenhanced", "price": "0.53", "region": "T", "data": "6/27", "status": "" },
  { "name": "Gas Guzzlers Extreme", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Gas Station Simulator", "price": "4.09", "region": "T", "data": "6/27", "status": "" },
  { "name": "Gefragt Gejagt - Das Spiel", "price": "21.85", "region": "E", "data": "6/27", "status": "" },
  { "name": "Get Even", "price": "0.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ghost Files: The Face of Guilt (Xbox Version)", "price": "3.21", "region": "A", "data": "6/26", "status": "" },
  { "name": "Glam's Incredible Run: Escape from Dukha", "price": "0.07", "region": "A", "data": "6/27", "status": "" },
  { "name": "Golazo! 2", "price": "1.33", "region": "A", "data": "6/27", "status": "" },
  { "name": "Grand Prix Rock 'N Racing", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Grand Theft Auto Online", "price": "4.01", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Grand Theft Auto V (Xbox One & Xbox Series X|S)", "price": "8.36", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Grand Theft Auto V: Premium Edition & Great White Shark C...", "price": "3.81", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Grand Theft Auto V: Premium Edition & Megalodon Shark Car...", "price": "6.39", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Grand Theft Auto V: Premium Edition & Whale Shark Card Bu...", "price": "4.40", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Grapple Dog", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Green Hell", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Griftlands", "price": "0.63", "region": "A", "data": "6/22", "status": "" },
  { "name": "Grindstone", "price": "3.27", "region": "T", "data": "6/27", "status": "" },
  { "name": "Gunborg: Dark Matters", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Guns, Gore and Cannoli", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Guns, Gore and Cannoli 2", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Hammerwatch: Heroic Bundle", "price": "0.50", "region": "A", "data": "6/27", "status": "" },
  { "name": "Haunted Halloween '86", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Haven", "price": "0.58", "region": "A", "data": "6/27", "status": "" },
  { "name": "Heart&Slash", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Heliborne", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Hell Pie", "price": "0.94", "region": "A", "data": "6/27", "status": "" },
  { "name": "Hello Neighbor 2", "price": "1.61", "region": "A", "data": "6/27", "status": "" },
  { "name": "Help Will Come Tomorrow", "price": "0.23", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Hexagroove: Tactical DJ", "price": "16.96", "region": "U", "data": "6/27", "status": "" },
  { "name": "Hotshot Racing", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Hyper Gunsport", "price": "0.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "Hyper Void", "price": "0.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "I, AI", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "I, AI (Xbox Series X|S)", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "INDIE BUNDLE: Shiness and Seasons after Fall", "price": "0.54", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Infernax", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Infinite Minigolf", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Inukari - Chase of Deception", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Istanbul: Digital Edition", "price": "2.73", "region": "T", "data": "6/27", "status": "" },
  { "name": "Jelly Brawl", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "JoJo's Bizarre Adventure All-Star Battle", "price": "8.64", "region": "E", "data": "6/27", "status": "" },
  { "name": "John Wick Hex", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Joy Ball Adventure", "price": "0.06", "region": "A", "data": "7/3/", "status": "" },
  { "name": "Just Dance® 2023 Edition", "price": "8.46", "region": "T", "data": "6/27", "status": "" },
  { "name": "Just Dance® 2023 Ultimate Edition", "price": "15.33", "region": "T", "data": "6/27", "status": "" },
  { "name": "Just Shapes & Beats", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Justice Sucks", "price": "0.74", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kaichu: The Kaiju Dating Sim", "price": "0.37", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kamikaze Veggies", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Katana Kata", "price": "0.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kerbal Space Program Enhanced Edition", "price": "1.87", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Kingdom Rush", "price": "1.65", "region": "T", "data": "6/27", "status": "" },
  { "name": "Kingdom Rush Frontiers", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kingdom Treasury Collection", "price": "0.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kingdom: New Lands", "price": "0.06", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kitaria Fables", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Knights and Bikes", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Kung Fu Fighting", "price": "0.12", "region": "A", "data": "7/1/", "status": "" },
  { "name": "L.A. Noire", "price": "2.81", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "LEGO® Bricktales", "price": "1.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "LOST ORBIT: Terminal Velocity", "price": "0.06", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ladders by POWGI", "price": "0.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lake", "price": "0.58", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lamentum", "price": "0.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lawn Mowing Simulator", "price": "1.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Layers of Fear (2023)", "price": "7.29", "region": "E", "data": "6/22", "status": "" },
  { "name": "Legend of Keepers: Complete Edition", "price": "1.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "Letterbox by POWGI", "price": "0.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "Light & Dark Bundle", "price": "0.90", "region": "A", "data": "11/2", "status": "" },
  { "name": "Little Mage Adventure", "price": "0.06", "region": "A", "data": "6/29", "status": "" },
  { "name": "Little Misfortune", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "Little Nightmares", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lotus Reverie: First Nexus", "price": "0.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Luckslinger", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lumberjack Simulator", "price": "0.88", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lumini", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Lunch A Palooza", "price": "0.34", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "METAL GEAR SURVIVE", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "MXGP2", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Machinarium", "price": "0.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Machinarium & Creaks Bundle", "price": "1.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Madden NFL 19", "price": "28.37", "region": "C", "data": "12/3", "status": "" },
  { "name": "Madden NFL 22 Xbox One", "price": "15.44", "region": "A", "data": "12/3", "status": "" },
  { "name": "Madden NFL 22 Xbox Series X|S", "price": "17.97", "region": "A", "data": "12/3", "status": "" },
  { "name": "Madden NFL 23 Xbox One", "price": "20.53", "region": "A", "data": "12/3", "status": "" },
  { "name": "Madden NFL 23 Xbox Series X|S", "price": "24.06", "region": "A", "data": "12/3", "status": "" },
  { "name": "Madden NFL 24 Deluxe Edition Xbox Series X|S & Xbox One + Limited Time Bonus", "price": "63.53", "region": "A", "data": "7/23", "status": "" },
  { "name": "Mafia II: Definitive Edition", "price": "2.50", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Mafia III: Definitive Edition", "price": "2.50", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Maneater Apex Edition", "price": "1.58", "region": "A", "data": "6/27", "status": "" },
  { "name": "Manifold Garden", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Manual Samuel", "price": "0.04", "region": "A", "data": "6/27", "status": "" },
  { "name": "Many Faces: Console Edition", "price": "0.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mark of the Ninja: Remastered", "price": "0.32", "region": "A", "data": "6/22", "status": "" },
  { "name": "Mars Horizon", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mech Armada", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Megaquarium", "price": "0.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "Microsoft 365 Family", "price": "0.00", "region": "U", "data": "12/1", "status": "" },
  { "name": "Microsoft 365 Personal", "price": "0.00", "region": "U", "data": "12/1", "status": "" },
  { "name": "Mighty Switch Force! Collection", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Milky Way Prince - The Vampire Star", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mini Madness", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Minoria", "price": "0.68", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Mittelborg: City of Mages", "price": "0.13", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mixups by POWGI", "price": "0.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mixx Island: Remix Plus", "price": "0.64", "region": "A", "data": "7/1/", "status": "" },
  { "name": "Monster Boy and the Cursed Kingdom", "price": "0.90", "region": "A", "data": "6/27", "status": "" },
  { "name": "Monster Energy Supercross - The Official Videogame 2", "price": "1.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Monster Energy Supercross 2 - Special Edition", "price": "2.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "Monster Prom: XXL", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Moo Lander", "price": "0.70", "region": "A", "data": "6/27", "status": "" },
  { "name": "Moon Raider", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Moonlighter: Complete Edition", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "MotoGP™20", "price": "0.90", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mr. Prepper", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mr. Run and Jump", "price": "6.13", "region": "T", "data": "7/24", "status": "" },
  { "name": "Multidimensions and Dreams", "price": "0.80", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Munchkin: Quacked Quest", "price": "0.58", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mutant Football League", "price": "0.18", "region": "A", "data": "6/27", "status": "" },
  { "name": "Mutant Football League - Dynasty Edition", "price": "1.24", "region": "T", "data": "6/27", "status": "" },
  { "name": "NARUTO SHIPPUDEN: Ultimate Ninja STORM Legacy", "price": "1.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "NBA 2K23 Digital Deluxe Edition", "price": "5.41", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "NEScape!", "price": "0.69", "region": "T", "data": "6/27", "status": "" },
  { "name": "NHL® 23 X-Factor Edition Xbox One & Xbox Series X|S", "price": "12.69", "region": "T", "data": "7/4/", "status": "" },
  { "name": "NHL® 23 Xbox One", "price": "8.88", "region": "T", "data": "7/4/", "status": "" },
  { "name": "NHL® 23 Xbox Series X|S", "price": "10.15", "region": "T", "data": "7/4/", "status": "" },
  { "name": "Need for Speed™ Unbound", "price": "10.83", "region": "A", "data": "6/22", "status": "" },
  { "name": "Need for Speed™ Unbound Palace Edition", "price": "12.63", "region": "A", "data": "7/4/", "status": "" },
  { "name": "New Tales from the Borderlands: Deluxe Edition", "price": "12.67", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Newfound Courage", "price": "0.13", "region": "A", "data": "6/27", "status": "" },
  { "name": "Nexomon", "price": "0.31", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ni no Kuni Wrath of the White Witch™ Remastered", "price": "7.20", "region": "E", "data": "6/27", "status": "" },
  { "name": "Ninja Warrior Epic Quest", "price": "0.14", "region": "A", "data": "5/31", "status": "" },
  { "name": "Nobody Saves the World", "price": "1.35", "region": "A", "data": "6/27", "status": "" },
  { "name": "Nobody Saves the World + Frozen Hearth Bundle", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Not For Broadcast", "price": "4.98", "region": "E", "data": "6/27", "status": "" },
  { "name": "Nova Lands", "price": "1.03", "region": "A", "data": "6/21", "status": "" },
  { "name": "ONE PIECE: PIRATE WARRIORS 4", "price": "1.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Observer: System Redux", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Oceanhorn - Monster of Uncharted Seas", "price": "0.15", "region": "A", "data": "6/27", "status": "" },
  { "name": "OlliOlli World", "price": "7.22", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "OneShot: World Machine Edition", "price": "0.69", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Operation: Tango", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Operencia: The Stolen Sun", "price": "0.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Outbreak Co-Op Anthology", "price": "0.52", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "PC Building Simulator", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "PUSS!", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Paint the Town Red", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Pang Adventures", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Party Hard 2", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Perfect Traffic Simulator", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Phantom Doctrine", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Plague Inc: Evolved", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Planet Cube: Edge", "price": "0.64", "region": "A", "data": "6/27", "status": "" },
  { "name": "Planetbase", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Poker Club", "price": "0.64", "region": "A", "data": "6/27", "status": "" },
  { "name": "Police Simulator: Patrol Officers", "price": "9.19", "region": "E", "data": "6/27", "status": "" },
  { "name": "Potion Permit", "price": "0.85", "region": "A", "data": "6/27", "status": "" },
  { "name": "Prison Tycoon: Under New Management", "price": "1.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Pro Gymnast Simulator", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Project Snaqe", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Promesa", "price": "0.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Protocol", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Punch Club", "price": "0.10", "region": "A", "data": "6/27", "status": "" },
  { "name": "Pure Chase 80's", "price": "0.98", "region": "T", "data": "6/27", "status": "" },
  { "name": "Pure Chess Grandmaster Edition", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Pure Pool", "price": "0.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "Pushy and Pully in Blockland", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Quake", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "RAGE 2", "price": "1.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "RAGE 2: Deluxe Edition", "price": "2.71", "region": "A", "data": "6/27", "status": "" },
  { "name": "RC Rush", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "RE:CALL", "price": "0.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "REDO!", "price": "1.10", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "RICO", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rabbids Invasion : The Interactive TV Show", "price": "0.15", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rally Rock 'N Racing", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ravenlok", "price": "1.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ravenous Devils", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Real Heroes: Firefighter HD", "price": "0.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Red Dead Redemption 2: Ultimate Edition", "price": "8.42", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Red Wings: Aces of the Sky", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Redout: Lightspeed Edition", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "Remothered: Tormented Fathers", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Riders Republic™", "price": "5.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rift Keeper", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rift Racoon", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rip Them Off", "price": "0.18", "region": "A", "data": "6/27", "status": "" },
  { "name": "River City Girls", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Riverbond", "price": "0.29", "region": "A", "data": "6/27", "status": "" },
  { "name": "Road Redemption", "price": "0.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rock 'N Racing Bundle", "price": "0.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rock 'N Racing Off Road DX", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rogue Legacy", "price": "0.06", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rogue Legacy 2", "price": "1.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Romancelvania", "price": "1.15", "region": "A", "data": "6/27", "status": "" },
  { "name": "Rubber Bandits", "price": "1.37", "region": "T", "data": "6/27", "status": "" },
  { "name": "SCARLET NEXUS", "price": "3.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "SD GUNDAM BATTLE ALLIANCE", "price": "8.66", "region": "E", "data": "6/27", "status": "" },
  { "name": "SENSEs: Midnight", "price": "8.03", "region": "I", "data": "6/22", "status": "" },
  { "name": "SHMUPS Pack 2x1", "price": "0.31", "region": "A", "data": "6/27", "status": "" },
  { "name": "SOULCALIBUR VI", "price": "1.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "STAR WARS Jedi: Fallen Order™", "price": "5.13", "region": "A", "data": "12/3", "status": "" },
  { "name": "STAR WARS Jedi: Fallen Order™ Deluxe Edition", "price": "6.86", "region": "A", "data": "1/1/", "status": "" },
  { "name": "STAY", "price": "0.12", "region": "A", "data": "6/27", "status": "" },
  { "name": "SWORD ART ONLINE Alicization Lycoris Deluxe Edition", "price": "5.51", "region": "A", "data": "6/27", "status": "" },
  { "name": "SWORD ART ONLINE: FATAL BULLET Complete Edition", "price": "9.50", "region": "I", "data": "6/27", "status": "" },
  { "name": "Sail Forth", "price": "0.91", "region": "A", "data": "6/27", "status": "" },
  { "name": "Sam & Max Save the World", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Sam & Max: Beyond Time and Space", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Schlag den Star - Das 2. Spiel", "price": "10.81", "region": "E", "data": "6/27", "status": "" },
  { "name": "Sea Salt", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Severed Steel", "price": "0.65", "region": "A", "data": "6/27", "status": "" },
  { "name": "Shady Part of Me", "price": "0.96", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Shantae and the Seven Sirens", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Shark Pinball", "price": "0.15", "region": "A", "data": "7/1/", "status": "" },
  { "name": "She Sees Red Interactive Movie", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Sheepo", "price": "0.38", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Ship Graveyard Simulator", "price": "0.53", "region": "A", "data": "6/27", "status": "" },
  { "name": "Sid Meier’s Civilization® VI Anthology", "price": "9.61", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Sid Meier’s Civilization® VI Platinum Edition", "price": "5.57", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Simulator Pack: Treasure Hunter Simulator and Gold Rush: The Game (DOUBLE BUNDLE)", "price": "8.03", "region": "E", "data": "6/27", "status": "" },
  { "name": "Skautfold: Usurper", "price": "0.77", "region": "A", "data": "6/23", "status": "" },
  { "name": "Skelattack", "price": "0.67", "region": "T", "data": "6/27", "status": "" },
  { "name": "Sky Rogue", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Slap the Rocks", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Smart Moves 2", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Snooker 19", "price": "0.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "Snooker 19 Gold Edition", "price": "0.84", "region": "A", "data": "6/27", "status": "" },
  { "name": "SnowRunner - 1-Anniversary Edition", "price": "7.61", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "Song of Horror", "price": "3.85", "region": "A", "data": "6/27", "status": "" },
  { "name": "Soundfall", "price": "2.04", "region": "T", "data": "6/27", "status": "" },
  { "name": "South Park™: The Stick of Truth ™", "price": "0.45", "region": "A", "data": "6/27", "status": "" },
  { "name": "South of the Circle", "price": "0.45", "region": "A", "data": "6/27", "status": "" },
  { "name": "Space Accident", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Space Engineers", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "Space Engineers: Ultimate Edition 2022", "price": "1.89", "region": "A", "data": "6/27", "status": "" },
  { "name": "Space Warlord Organ Trading Simulator", "price": "0.68", "region": "A", "data": "6/27", "status": "" },
  { "name": "Spacelines from the Far Out", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Sparkle Bundle", "price": "0.51", "region": "A", "data": "12/3", "status": "" },
  { "name": "Speed or Death", "price": "0.37", "region": "A", "data": "7/1/", "status": "" },
  { "name": "Speedway Racing", "price": "1.65", "region": "T", "data": "6/27", "status": "" },
  { "name": "Spirit Roots", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Starlink: Battle for Atlas™ - Deluxe edition", "price": "1.60", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Starpoint Gemini 2", "price": "5.10", "region": "H", "data": "6/27", "status": "" },
  { "name": "Starpoint Gemini Warlords", "price": "6.56", "region": "M", "data": "6/27", "status": "" },
  { "name": "Startup Company Console Edition", "price": "0.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Steel Rain X", "price": "0.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "Stellar Interface", "price": "0.08", "region": "A", "data": "7/1/", "status": "" },
  { "name": "Steve Jackson's Sorcery!", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Streets of Rage 4", "price": "0.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "Streets of Rogue", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "Summer in Mara + Deiland Bundle", "price": "0.58", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Super Arcade Football", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Super Arcade Racing", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Super Hydorah", "price": "1.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Super Pixel Kid", "price": "0.06", "region": "A", "data": "6/29", "status": "" },
  { "name": "Super Pixel Racers", "price": "0.30", "region": "A", "data": "6/27", "status": "" },
  { "name": "Super Rebellion", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Super Toy Cars", "price": "0.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Super Toy Cars Offroad", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "SuperMash", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "Surviving Franchise Bundle", "price": "1.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Surviving Mars - Starter Bundle", "price": "1.67", "region": "A", "data": "6/27", "status": "" },
  { "name": "Swordship", "price": "0.80", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Symmetry", "price": "0.10", "region": "A", "data": "6/27", "status": "" },
  { "name": "Synchro Hedgehogs", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Sébastien Loeb Rally EVO", "price": "0.16", "region": "A", "data": "6/27", "status": "" },
  { "name": "TEKKEN 7 - Originals Edition", "price": "2.71", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tales of Arise", "price": "6.62", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tales of Vesperia™: Definitive Edition", "price": "0.96", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tales of the Neon Sea", "price": "0.91", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tangle Tower", "price": "0.23", "region": "A", "data": "6/27", "status": "" },
  { "name": "Teenage Mutant Ninja Turtles: Shredder's Revenge", "price": "1.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "Teenage Mutant Ninja Turtles: The Cowabunga Collection", "price": "8.19", "region": "T", "data": "6/27", "status": "" },
  { "name": "Tell Me Why: Chapters 1-3", "price": "0.00", "region": "U", "data": "7/1/", "status": "" },
  { "name": "TerraTech", "price": "1.81", "region": "T", "data": "6/27", "status": "" },
  { "name": "TerraTech: Prospector Edition", "price": "3.55", "region": "T", "data": "6/27", "status": "" },
  { "name": "Terror of Hemasaurus", "price": "0.56", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Banner Saga", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Banner Saga 2", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Blackout Club", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Colonists", "price": "0.83", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Crew® 2 Special Edition", "price": "1.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Dark Pictures Anthology House of Ashes", "price": "4.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Dark Pictures Anthology: Little Hope", "price": "4.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Dark Pictures Anthology: Man Of Medan", "price": "4.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Dark Side of the Moon: An Interactive FMV Thriller", "price": "0.51", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Darkest Tales", "price": "4.09", "region": "T", "data": "6/27", "status": "" },
  { "name": "The Division 2 - Warlords of New York - Ultimate Edition", "price": "4.81", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "The Division 2 - Warlords of New York Edition", "price": "3.61", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Elder Scrolls V: Skyrim Special Edition", "price": "2.00", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Entropy Centre", "price": "4.85", "region": "I", "data": "6/27", "status": "" },
  { "name": "The Escapists: Supermax Edition", "price": "1.01", "region": "A", "data": "4/30", "status": "" },
  { "name": "The Evil Within", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Evil Within (PC)", "price": "0.39", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Evil Within Digital Bundle", "price": "0.55", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Evil Within® 2", "price": "1.22", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Fairy's Song", "price": "0.46", "region": "A", "data": "7/1/", "status": "" },
  { "name": "The First Tree", "price": "0.11", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Game of Life 2", "price": "0.69", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Gardener and the Wild Vines", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Gunk", "price": "0.86", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "The Incredible Adventures of Van Helsing: Complete Trilogy", "price": "0.39", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Jackbox Party Pack 2", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Jackbox Party Pack 4", "price": "0.50", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Jackbox Party Pack 7", "price": "1.03", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Jackbox Party Starter", "price": "0.74", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Legend of Tianding", "price": "3.82", "region": "T", "data": "6/27", "status": "" },
  { "name": "The Library of Babel", "price": "0.76", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Lord of the Rings: Adventure Card Game - Definitive Edition", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Magic Circle: Gold Edition", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Medium", "price": "1.72", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Outer Worlds", "price": "5.57", "region": "E", "data": "6/27", "status": "" },
  { "name": "The Outer Worlds", "price": "10.72", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "The Outer Worlds: Spacer's Choice Edition", "price": "18.28", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "The Riftbreaker", "price": "1.03", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Riftbreaker Deluxe Edition", "price": "1.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Sexy Brutale", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Sojourn", "price": "0.44", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Spectrum Retreat", "price": "0.18", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Surge", "price": "1.14", "region": "T", "data": "6/27", "status": "GOLD" },
  { "name": "The Touryst", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Wanderer: Frankenstein's Creature", "price": "0.60", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "The Witch's House MV", "price": "0.52", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Witcher 3: Wild Hunt", "price": "4.01", "region": "A", "data": "6/27", "status": "" },
  { "name": "The Witcher 3: Wild Hunt – Complete Edition", "price": "6.62", "region": "A", "data": "6/27", "status": "" },
  { "name": "They Are Billions", "price": "0.52", "region": "A", "data": "6/27", "status": "" },
  { "name": "Thimbleweed Park", "price": "0.57", "region": "A", "data": "6/27", "status": "" },
  { "name": "This War of Mine - Complete Edition", "price": "0.31", "region": "A", "data": "6/27", "status": "" },
  { "name": "Thronebreaker: The Witcher Tales", "price": "1.44", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ticket to Ride", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Time Loader", "price": "0.26", "region": "A", "data": "6/27", "status": "" },
  { "name": "Time Of War, Arkano'90", "price": "0.69", "region": "A", "data": "6/23", "status": "" },
  { "name": "Tin Can", "price": "4.49", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Tin Can: Supporter Edition", "price": "5.61", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Titan Chaser", "price": "0.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tom Clancy's Ghost Recon® Breakpoint", "price": "2.41", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tom Clancy's Ghost Recon® Breakpoint Deluxe Edition", "price": "2.89", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tom Clancy's Rainbow Six® Siege Operator Edition", "price": "14.44", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tom Clancy’s Ghost Recon® Wildlands Ultimate Edition", "price": "3.81", "region": "A", "data": "6/27", "status": "" },
  { "name": "Total Arcade Racing", "price": "0.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trailblazers", "price": "0.12", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trailmakers", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trailmakers Deluxe Edition", "price": "1.09", "region": "A", "data": "6/27", "status": "" },
  { "name": "Train Sim World® 3: Deluxe Edition & Loco Bundle", "price": "2.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Train Station Renovation", "price": "0.37", "region": "A", "data": "6/27", "status": "" },
  { "name": "Train Station Simulator", "price": "0.31", "region": "A", "data": "6/27", "status": "" },
  { "name": "Train Valley: Console Edition", "price": "0.64", "region": "T", "data": "6/27", "status": "" },
  { "name": "TramSim: Console Edition - Deluxe", "price": "23.00", "region": "T", "data": "6/27", "status": "" },
  { "name": "Treasure Hunter Simulator", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "Tribal Pass", "price": "0.10", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trifox", "price": "0.80", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trigger Witch", "price": "0.34", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trine 4: The Nightmare Prince", "price": "0.43", "region": "A", "data": "6/27", "status": "" },
  { "name": "Trophy", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Twin Mirror", "price": "1.60", "region": "A", "data": "6/27", "status": "" },
  { "name": "Typoman", "price": "0.14", "region": "A", "data": "6/27", "status": "" },
  { "name": "UNO® Ultimate Edition", "price": "1.50", "region": "T", "data": "6/27", "status": "" },
  { "name": "Under the Jolly Roger", "price": "0.56", "region": "A", "data": "6/27", "status": "" },
  { "name": "Under the Jolly Roger - Complete Edition", "price": "1.08", "region": "A", "data": "6/27", "status": "" },
  { "name": "Unit 4: Couch Attack Bundle", "price": "0.54", "region": "A", "data": "12/3", "status": "" },
  { "name": "Unruly Heroes", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Until the Last Plane", "price": "0.40", "region": "A", "data": "6/27", "status": "" },
  { "name": "Urbek City Builder", "price": "0.76", "region": "A", "data": "6/27", "status": "" },
  { "name": "Vagante", "price": "0.85", "region": "T", "data": "6/27", "status": "" },
  { "name": "Valfaris", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Valley", "price": "0.13", "region": "A", "data": "6/27", "status": "" },
  { "name": "Vegas Party", "price": "0.04", "region": "A", "data": "6/27", "status": "" },
  { "name": "Vengeful Heart", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Venus: Improbable Dream", "price": "0.28", "region": "A", "data": "6/27", "status": "" },
  { "name": "Vermintide - Digital Value Pack", "price": "1.60", "region": "A", "data": "3/7/", "status": "" },
  { "name": "WATCH_DOGS™", "price": "0.27", "region": "A", "data": "6/27", "status": "" },
  { "name": "WRC Collection FIA World Rally Championship", "price": "2.55", "region": "A", "data": "8/31", "status": "" },
  { "name": "WWE 2K23 for Xbox One", "price": "21.50", "region": "A", "data": "7/4/", "status": "" },
  { "name": "Watch Dogs: Legion - Deluxe Edition", "price": "2.71", "region": "A", "data": "6/27", "status": "" },
  { "name": "Watch Dogs®2 - Deluxe Edition", "price": "2.05", "region": "A", "data": "6/27", "status": "" },
  { "name": "Watch Dogs®2 - Gold Edition", "price": "2.41", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "Watch Dogs®: Legion Ultimate Edition", "price": "5.61", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wave Break", "price": "0.68", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wayward Strand", "price": "4.37", "region": "T", "data": "6/27", "status": "" },
  { "name": "We Are The Caretakers", "price": "3.66", "region": "T", "data": "6/27", "status": "" },
  { "name": "We Happy Few", "price": "0.51", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "We Happy Few Digital Deluxe", "price": "0.68", "region": "A", "data": "6/27", "status": "GOLD" },
  { "name": "We Were Here Forever", "price": "3.43", "region": "T", "data": "6/22", "status": "" },
  { "name": "Wer weiß denn sowas? - Das Spiel", "price": "10.81", "region": "E", "data": "6/27", "status": "" },
  { "name": "Wer weiß denn sowas? Complete Edition", "price": "21.03", "region": "E", "data": "6/27", "status": "" },
  { "name": "Wheel Of Fortune®", "price": "0.42", "region": "A", "data": "6/27", "status": "" },
  { "name": "White Shadows", "price": "0.46", "region": "A", "data": "6/27", "status": "" },
  { "name": "Windjammers 2", "price": "0.68", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wolfenstein II: Standard Edition", "price": "1.13", "region": "T", "data": "6/27", "status": "" },
  { "name": "Wolfenstein: Alt History Collection", "price": "2.17", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wolfenstein: The New Order", "price": "0.36", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wolfenstein: The Old Blood", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wolfenstein® II: The New Colossus™", "price": "1.22", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wolfenstein®: The Two-Pack", "price": "0.48", "region": "A", "data": "6/27", "status": "" },
  { "name": "Wonder Boy: The Dragon's Trap", "price": "0.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Work from Home", "price": "3.82", "region": "T", "data": "6/27", "status": "" },
  { "name": "World of Outlaws: Dirt Racing", "price": "1.61", "region": "A", "data": "6/27", "status": "" },
  { "name": "World of Outlaws: Dirt Racing Gold Edition", "price": "14.04", "region": "A", "data": "6/27", "status": "" },
  { "name": "World of Van Helsing: Deathtrap", "price": "0.12", "region": "A", "data": "6/27", "status": "" },
  { "name": "Worlds of Magic: Planar Conquest", "price": "0.35", "region": "A", "data": "6/27", "status": "" },
  { "name": "XEL - Complete Edition", "price": "1.01", "region": "A", "data": "7/1/", "status": "" },
  { "name": "Young Souls", "price": "0.86", "region": "A", "data": "6/27", "status": "" },
  { "name": "Youtubers Life - OMG Edition", "price": "0.48", "region": "A", "data": "6/27", "status": "" },
  { "name": "Youtubers Life 2", "price": "5.62", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ys Origin", "price": "0.32", "region": "A", "data": "6/27", "status": "" },
  { "name": "Yu-Gi-Oh! Legacy of the Duelist", "price": "0.20", "region": "A", "data": "6/27", "status": "" },
  { "name": "Yu-Gi-Oh! Legacy of the Duelist : Link Evolution", "price": "1.89", "region": "T", "data": "6/27", "status": "" },
  { "name": "Z-Warp", "price": "0.24", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ziggurat", "price": "0.21", "region": "A", "data": "6/27", "status": "" },
  { "name": "Ziggurat 2", "price": "0.82", "region": "A", "data": "6/27", "status": "" },
  { "name": "theHunter: Call of the Wild™ - Greenhorn Bundle", "price": "1.61", "region": "A", "data": "6/27", "status": "" },
  { "name": "theHunter: Call of the Wild™ - Seasoned Hunter Bundle", "price": "2.00", "region": "A", "data": "6/27", "status": "" }
]



console.log(arr.length);
const sortArr = arr.sort(function (a, b) {
  if (a.name > b.name) {
    return 1;
  }
  if (a.name < b.name) {
    return -1;
  }
  return 0;
});

function floor(price) {
  let enterPrice = Number(price)
  const lastNum = Number(enterPrice.toString().split('').pop())

  switch (lastNum) {
    case 1:
      enterPrice += 4
      break;
    case 2:
      enterPrice += 3
      break;
    case 3:
      enterPrice += 2
      break;
    case 4:
      enterPrice += 1
      break;
    case 6:
      enterPrice += 4
      break;
    case 7:
      enterPrice += 3
      break;
    case 8:
      enterPrice += 2
      break;
    case 9:
      enterPrice += 1
      break;
    default:
      enterPrice
      break;
  }
  return enterPrice;
}

function result() {
  const value = Number(input.value) + .1
  const res = value * usd
  const finishRes = res + resSwitсh(input.value)
  output.innerHTML = floor(finishRes.toFixed())
}

function resultFromList(price) {
  const value = Number(price) + .1
  const res = value * usd + 40
  const finishRes = res + resSwitсh(price)
  return floor(finishRes.toFixed())
}

function resSwitсh(value) {
  let a;
  if (value <= 1) {
    a = 50
  } else if (value > 1 && value <= 5) {
    a = 60
  } else if (value > 5 && value <= 10) {
    a = 80
  } else if (value > 10 && value <= 15) {
    a = 95
  } else if (value > 15 && value <= 20) {
    a = 100
  } else if (value > 20 && value <= 25) {
    a = 150
  } else if (value > 25) {
    a = 170
  }
  return a
}

input.oninput = result


sortArr.map((a) => {
  // const status = 
  const item = document.createElement('li')
  const arrData = a.data.split('/').reverse('').join('/')
  let res;
  let flag;
  if (a.region == 'A') {
    res = resultFromList(a.price)
    flag = "🇦🇷"
  } else if (a.region == 'T') {
    res = resultFromList(a.price)
    flag = "🇹🇷"
  } else {
    res = 'Уточнить стоимость в ЛС'
  }

  item.innerHTML = res == 'Уточнить стоимость в ЛС' ? `${a.name}: ${res} до:${arrData}` : `${a.name}:${res}&#8381; ${flag}  до:${arrData}${a.status}`
  // &#8381; ${ flag } до:${ arrData }${ a.status }
  list.append(item)
})
// 
function showMenu() {
  showBtn.classList.add('active')
  list.classList.add('active');
  showBtn.innerHTML = 'Скрыть Список'
  showBtn.style.background = 'red'

}

function hiddenMenu() {
  showBtn.classList.remove('active')
  list.classList.remove('active');
  showBtn.innerHTML = 'Показать Список'
  showBtn.style.background = 'greenyellow'
}
