const input = document.querySelector('.input');
const output = document.querySelector('.output-res');
const list = document.querySelector('.list')
const showBtn = document.querySelector('.show')


showBtn.addEventListener('click', () => {
  showBtn.classList.contains('active') ?
    hiddenMenu() : showMenu()
})

let usd = 110;

const arr = [
  { "name": "A Plague Tale Bundle", "price": "19.09", "region": "T", "data": "11/7/", "status": "" },
  { "name": "ABZU", "price": "0.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "ADVERSE", "price": "0.05", "region": "A", "data": "11/7/", "status": "" },
  { "name": "AO Tennis 2", "price": "0.33", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Absolute Deduction bundle", "price": "6.69", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Ad Infinitum", "price": "10.50", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Adventurous Mind", "price": "5.00", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Aery Series Bundle", "price": "1.15", "region": "A", "data": "11/5/", "status": "" },
  { "name": "After Wave: Downfall", "price": "3.96", "region": "I", "data": "11/7/", "status": "" },
  { "name": "Agatha Christie Collection", "price": "2.14", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Alan Wake Remastered", "price": "1.13", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Albedo: Eyes From Outer Space", "price": "0.04", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Alien: Isolation", "price": "2.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Aliens: Fireteam Elite Into the Hive Edition", "price": "5.74", "region": "E", "data": "11/7/", "status": "GOLD" },
  { "name": "Aliens: Fireteam Elite Ultimate Edition", "price": "9.51", "region": "E", "data": "11/1/", "status": "" },
  { "name": "Allison's Diary: Rebirth", "price": "0.24", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Almost There: The Platformer", "price": "0.08", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Alone in the Dark", "price": "10.03", "region": "A", "data": "1/16/", "status": "" },
  { "name": "Alone in the Dark - Digital Deluxe Edition", "price": "11.57", "region": "A", "data": "1/16/", "status": "" },
  { "name": "Anodyne", "price": "0.06", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Antarctica 88", "price": "0.15", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Asdivine Cross", "price": "0.31", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Assassin's Creed Chronicles – Trilogy", "price": "0.21", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed Legendary Collection", "price": "4.29", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed Triple Pack: Black Flag, Unity, Syndicate", "price": "0.64", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Odyssey - DELUXE EDITION", "price": "1.71", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Odyssey - GOLD EDITION", "price": "2.14", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Origins - GOLD EDITION", "price": "2.14", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Rogue", "price": "0.34", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Syndicate Gold Edition", "price": "1.86", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Valhalla Complete Edition", "price": "8.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin's Creed® Valhalla Deluxe Edition", "price": "3.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin’s Creed® Rogue Remastered", "price": "0.71", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin’s Creed® Valhalla + Immortals Fenyx Rising™ Bundle", "price": "3.71", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assassin’s Creed® Valhalla + Watch Dogs®: Legion Bundle", "price": "3.71", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assetto Corsa", "price": "0.21", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Assetto Corsa Competizione", "price": "2.53", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Asterix & Obelix XXL Collection", "price": "6.86", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Atomic Heart - Premium Edition", "price": "31.57", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Attack on Titan 2: Final Battle", "price": "21.73", "region": "A", "data": "11/7/", "status": "" },
  { "name": "BACK TO CHILDHOOD: Classic Games Collection", "price": "5.71", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "BATTLESHIP®", "price": "0.13", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "BEB: Super Mega Bundle", "price": "0.11", "region": "A", "data": "11/7/", "status": "" },
  { "name": "BIOHAZARD 7 Gold Edition & VILLAGE Gold Edition バンドル", "price": "23.93", "region": "J", "data": "11/1/", "status": "" },
  { "name": "BIOHAZARD 7 Gold Edition & VILLAGE Gold Edition バンドル Z Version", "price": "23.93", "region": "J", "data": "11/1/", "status": "" },
  { "name": "BIOHAZARD 7 resident evil Gold Edition グロテスクVer.", "price": "13.28", "region": "J", "data": "11/1/", "status": "" },
  { "name": "BIOHAZARD 7 resident evil グロテスクVer.", "price": "5.30", "region": "J", "data": "11/1/", "status": "" },
  { "name": "BIOHAZARD RE:3 Z Version", "price": "6.64", "region": "J", "data": "11/1/", "status": "" },
  { "name": "BIOHAZARD VILLAGE Z Version", "price": "13.28", "region": "J", "data": "11/1/", "status": "" },
  { "name": "BIOHAZARD VILLAGE Z version GOLD EDITION", "price": "15.95", "region": "J", "data": "11/1/", "status": "" },
  { "name": "Back 4 Blood", "price": "2.86", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Ball laB II", "price": "2.58", "region": "I", "data": "11/2/", "status": "" },
  { "name": "Ballotron", "price": "0.14", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Beat Souls", "price": "0.16", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Bee Simulator", "price": "0.08", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Big Pharma", "price": "0.25", "region": "A", "data": "11/7/", "status": "" },
  { "name": "BigChick", "price": "0.15", "region": "A", "data": "11/7/", "status": "" },
  { "name": "BioShock: The Collection", "price": "1.68", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Bish Bash Bots", "price": "0.73", "region": "A", "data": "11/3/", "status": "" },
  { "name": "Black Book", "price": "0.46", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Black Mirror", "price": "0.29", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Blair Witch", "price": "0.31", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Blasphemous", "price": "0.26", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Bloodstained: Ritual of the Night", "price": "1.90", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Boggle", "price": "0.10", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Book of Demons", "price": "0.40", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Borderlands 3", "price": "1.18", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Borderlands 3: Next Level Edition", "price": "1.38", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Borderlands 3: Super Deluxe Edition", "price": "2.50", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Borderlands 3: Ultimate Edition", "price": "3.86", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Borderlands Collection: Pandora's Box", "price": "38.16", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Borderlands Legendary Collection", "price": "3.86", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Borderlands: Game of the Year Edition", "price": "1.34", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Borderlands: The Handsome Collection", "price": "1.93", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Bramble: The Mountain King", "price": "0.74", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Brothers: a Tale of Two Sons", "price": "0.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "CODE VEIN", "price": "1.29", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Call of Toys: Tower Defense!", "price": "2.62", "region": "A", "data": "11/3/", "status": "" },
  { "name": "Chef Life - AL FORNO EDITION", "price": "10.28", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Chess Royal", "price": "0.10", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Chivalry 2", "price": "0.82", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Chivalry 2 Special Edition", "price": "1.02", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Chorus", "price": "1.13", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Chrome Wolf", "price": "0.43", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Cloudpunk", "price": "0.25", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Control", "price": "1.50", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Corpse Party", "price": "0.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Cosmic Top Secret", "price": "0.41", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Crime Boss: Rockay City", "price": "4.43", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Crown Trick", "price": "0.64", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Crusader Kings III", "price": "1.02", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Cult of the Lamb", "price": "3.25", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Cult of the Lamb: Cultist Edition", "price": "3.60", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Cyber Tank", "price": "0.18", "region": "A", "data": "11/4/", "status": "" },
  { "name": "DARKLAND 3", "price": "0.04", "region": "A", "data": "11/13", "status": "" },
  { "name": "DC's Justice League: Cosmic Chaos", "price": "9.00", "region": "A", "data": "11/7/", "status": "" },
  { "name": "DE-EXIT - Eternal Matters", "price": "2.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "DEAD ISLAND 2 GOLD EDITION", "price": "18.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "DEADCRAFT", "price": "0.31", "region": "A", "data": "11/7/", "status": "" },
  { "name": "DEADCRAFT Deluxe Edition", "price": "0.49", "region": "A", "data": "11/7/", "status": "" },
  { "name": "DEATHLOOP", "price": "5.30", "region": "T", "data": "11/1/", "status": "" },
  { "name": "DEATHLOOP Deluxe Edition", "price": "5.74", "region": "T", "data": "11/1/", "status": "" },
  { "name": "DMC4SE Demon Hunter Bundle", "price": "4.98", "region": "H", "data": "11/1/", "status": "" },
  { "name": "DOOM Eternal Deluxe Edition", "price": "7.00", "region": "T", "data": "11/1/", "status": "" },
  { "name": "DOOM Eternal: Year One Pass", "price": "4.03", "region": "T", "data": "11/1/", "status": "" },
  { "name": "DOOM Eternal: Year One Pass (PC)", "price": "4.03", "region": "T", "data": "11/1/", "status": "" },
  { "name": "DRAGON BALL FIGHTERZ - Ultimate Edition", "price": "5.04", "region": "T", "data": "11/7/", "status": "" },
  { "name": "DYSMANTLE", "price": "0.32", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Darksiders Fury's Collection - War and Death", "price": "0.29", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dawn of the Monsters", "price": "0.61", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "DayZ", "price": "1.22", "region": "A", "data": "11/1/", "status": "" },
  { "name": "DayZ Livonia Edition", "price": "1.57", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Days of Doom", "price": "4.86", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead Island 2", "price": "13.98", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead Island Definitive Collection", "price": "0.21", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead Island Retro Revenge", "price": "0.03", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead Rising", "price": "4.13", "region": "J", "data": "11/1/", "status": "" },
  { "name": "Dead Rising 2", "price": "4.13", "region": "J", "data": "11/1/", "status": "" },
  { "name": "Dead Rising 2 Off the Record", "price": "3.81", "region": "B", "data": "11/1/", "status": "" },
  { "name": "Dead Rising 3: Apocalypse Edition", "price": "2.19", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Dead Rising 4", "price": "7.07", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Dead Rising Triple Bundle Pack", "price": "8.56", "region": "J", "data": "11/1/", "status": "" },
  { "name": "Dead Space", "price": "15.43", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead Space Digital Deluxe Edition", "price": "18.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead by Daylight", "price": "0.46", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead by Daylight: Silent Hill Edition", "price": "1.22", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead by Daylight: ULTIMATE EDITION", "price": "1.61", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dead by Daylight: ULTIMATE EDITION", "price": "1.61", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Deep Rock Galactic - Deluxe Edition", "price": "0.54", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Deep Rock Galactic - Ultimate Edition", "price": "0.67", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles Digital Deluxe Edition", "price": "8.84", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Destiny - The Collection", "price": "1.70", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Destroy All Humans! 2 - Reprobed: Single Player (X1)", "price": "7.95", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Detective Reborn Bundle", "price": "9.01", "region": "E", "data": "11/7/", "status": "" },
  { "name": "Devil May Cry 4 Special Edition", "price": "3.06", "region": "B", "data": "11/1/", "status": "" },
  { "name": "Devil May Cry 5 + Vergil", "price": "6.56", "region": "J", "data": "11/1/", "status": "" },
  { "name": "Devil May Cry 5 Deluxe + Vergil", "price": "11.31", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Devil May Cry 5 Special Edition", "price": "11.31", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Devil May Cry HD Collection", "price": "7.00", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Devil May Cry HD Collection & 4SE Bundle", "price": "10.50", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Diablo® IV - Digital Deluxe Edition", "price": "29.98", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Diablo® IV - Standard Edition", "price": "22.48", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Diablo® IV - Ultimate Edition", "price": "32.12", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Disciples: Liberation Digital Deluxe Edition", "price": "1.23", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Discolored", "price": "0.20", "region": "A", "data": "11/7/", "status": "" },
  { "name": "DmC Devil May Cry: Definitive Edition", "price": "5.53", "region": "I", "data": "11/1/", "status": "" },
  { "name": "Doki Doki Literature Club Plus!", "price": "0.49", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dolmen", "price": "1.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Donut County", "price": "0.16", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Dou", "price": "0.04", "region": "A", "data": "11/9/", "status": "" },
  { "name": "Dracula's Legacy Remastered", "price": "0.37", "region": "A", "data": "11/7/", "status": "" },
  { "name": "DreamWorks All-Star Kart Racing", "price": "22.20", "region": "I", "data": "11/2/", "status": "" },
  { "name": "DreamWorks All-Star Kart Racing Rally Edition", "price": "27.81", "region": "I", "data": "11/2/", "status": "" },
  { "name": "Dungeons 3", "price": "0.61", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dungeons 4", "price": "1.84", "region": "A", "data": "11/9/", "status": "" },
  { "name": "Dungeons 4 - Digital Deluxe Edition", "price": "2.21", "region": "A", "data": "11/9/", "status": "" },
  { "name": "Dying Light 2 Stay Human", "price": "5.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dying Light 2 Stay Human - Ultimate Edition", "price": "14.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Dying Light: The Following - Enhanced Edition", "price": "1.68", "region": "T", "data": "11/1/", "status": "" },
  { "name": "EA SPORTS FC™ 24 Standard Edition Xbox One & Xbox Series X|S", "price": "34.64", "region": "T", "data": "12/31", "status": "" },
  { "name": "EA SPORTS FC™ 24 Ultimate Edition Xbox One & Xbox Series X|S", "price": "49.49", "region": "T", "data": "11/1/", "status": "" },
  { "name": "EDENGATE: The Edge of Life", "price": "0.65", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Echo Generation", "price": "0.51", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Eiyuden Chronicle: Rising", "price": "1.50", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Escape Dead Island", "price": "0.11", "region": "A", "data": "12/31", "status": "" },
  { "name": "Escape Game - FORT BOYARD 2022", "price": "0.61", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Escape Game Fort Boyard", "price": "0.30", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Evil Dead: The Game", "price": "0.82", "region": "A", "data": "11/2/", "status": "" },
  { "name": "FATAL FRAME: Maiden of Black Water", "price": "8.80", "region": "A", "data": "11/1/", "status": "" },
  { "name": "FATAL FRAME: Maiden of Black Water Digital Deluxe Edition", "price": "12.10", "region": "A", "data": "11/1/", "status": "" },
  { "name": "FATAL FRAME: Mask of the Lunar Eclipse Digital Deluxe Edition", "price": "16.06", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Fallout 4", "price": "1.27", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Fallout 4 (PC)", "price": "0.96", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Fallout 4: Game of the Year Edition", "price": "2.52", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Fallout 4: Game of the Year Edition (PC)", "price": "2.52", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Fallout 76", "price": "2.47", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Fallout 76: The Pitt Deluxe Edition", "price": "7.00", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Family Feud®", "price": "6.14", "region": "N", "data": "11/7/", "status": "GOLD" },
  { "name": "Fantasy Defenders Complete Bundle: Defend the Rook & Legend of Keepers", "price": "5.80", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Farmer's Dynasty", "price": "0.12", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Finis", "price": "0.38", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Five Nights at Freddy's: Help Wanted", "price": "0.92", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Five Nights at Freddy's: Security Breach", "price": "1.23", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Football Manager 2024 Console", "price": "15.56", "region": "E", "data": "11/6/", "status": "" },
  { "name": "Fort Boyard", "price": "0.18", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "From Shadows Redux", "price": "0.05", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Fur Squadron", "price": "0.23", "region": "A", "data": "11/11", "status": "" },
  { "name": "Fusion Paradox", "price": "0.32", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Fusion Paradox (Xbox Series X|S)", "price": "0.32", "region": "A", "data": "11/1/", "status": "" },
  { "name": "GRIS", "price": "0.86", "region": "A", "data": "11/7/", "status": "" },
  { "name": "GYLT", "price": "4.65", "region": "E", "data": "11/1/", "status": "" },
  { "name": "Gangs of Sherwood – Lionheart Edition Pre-order", "price": "15.17", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Garfield Lasagna Party", "price": "0.82", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Get Even", "price": "0.43", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Ghost Trick: Phantom Detective", "price": "10.25", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Ghostbusters: Spirits Unleashed", "price": "0.61", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Ghostbusters: The Video Game Remastered", "price": "0.49", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Ghosts 'n Goblins Resurrection", "price": "6.15", "region": "C", "data": "11/1/", "status": "" },
  { "name": "Ghostwire: Tokyo", "price": "7.00", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Ghostwire: Tokyo Deluxe Edition", "price": "9.04", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Giana Sisters: Twisted Dreams - Director's Cut", "price": "0.04", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Gnomes Garden: Lost King", "price": "0.16", "region": "A", "data": "11/7/", "status": "" },
  { "name": "God's Trigger", "price": "0.32", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Golazo!", "price": "0.09", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Gord - Deluxe Edition", "price": "13.80", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Greyhill Incident - Abducted Edition", "price": "0.92", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Grow: Song of the Evertree", "price": "1.61", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Gunfire Reborn", "price": "2.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Halloween Pinball", "price": "0.10", "region": "A", "data": "11/11", "status": "" },
  { "name": "Hasbro Family Fun Pack", "price": "8.67", "region": "C", "data": "11/7/", "status": "GOLD" },
  { "name": "Hasbro Family Fun Pack Conquest Edition", "price": "8.67", "region": "C", "data": "11/7/", "status": "GOLD" },
  { "name": "Haunted House", "price": "3.24", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Have Fun Together", "price": "8.57", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Hazelight Bundle", "price": "5.49", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Hell Warders", "price": "0.06", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Hello Neighbor", "price": "0.21", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Hello Neighbor 2", "price": "0.98", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Hello Neighbor: Hide and Seek", "price": "0.31", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Hidden Cats in London", "price": "0.10", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Horace", "price": "1.20", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Hotel Transylvania 3: Monsters Overboard", "price": "2.50", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Hotel Transylvania: Scary-Tale Adventures", "price": "2.91", "region": "A", "data": "11/1/", "status": "" },
  { "name": "How To Survive 2", "price": "0.09", "region": "A", "data": "11/7/", "status": "" },
  { "name": "How to Survive: Storm Warning Edition", "price": "0.14", "region": "A", "data": "11/7/", "status": "" },
  { "name": "HyperParasite", "price": "0.06", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "INSIDE", "price": "1.15", "region": "T", "data": "11/7/", "status": "" },
  { "name": "INSIDE & LIMBO Bundle", "price": "1.55", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Immortal Realms: Vampire Wars", "price": "3.43", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Indivisible", "price": "0.95", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Inscryption", "price": "2.03", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Inspector Gadget - MAD Time Party", "price": "9.71", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Jagged Alliance 3", "price": "16.97", "region": "T", "data": "11/14", "status": "" },
  { "name": "Jeopardy!", "price": "0.21", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Journey to the Savage Planet", "price": "1.71", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Joy Ball Adventure", "price": "0.04", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Just Dance® 2023 Edition", "price": "7.07", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Killer Frequency", "price": "4.98", "region": "E", "data": "11/1/", "status": "" },
  { "name": "Killing Floor 2", "price": "0.57", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Killing Floor 2 - Ultimate Edition", "price": "8.61", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Kingdom Come: Deliverance", "price": "0.91", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Kingdom of Aurelia: Mystery of the Poisoned Dagger", "price": "0.65", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Koh-Lanta", "price": "0.72", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Kung Fu Fighting", "price": "0.04", "region": "A", "data": "11/1/", "status": "" },
  { "name": "L.A. Noire", "price": "2.00", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "LEGO® Star Wars™: The Skywalker Saga Galactic Edition", "price": "7.54", "region": "A", "data": "11/7/", "status": "" },
  { "name": "LIMBO", "price": "0.57", "region": "T", "data": "11/7/", "status": "" },
  { "name": "LUMINES REMASTERED", "price": "0.13", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Layers of Fear (2023)", "price": "6.42", "region": "E", "data": "11/1/", "status": "" },
  { "name": "Light & Dark Bundle", "price": "4.56", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Little Nightmares", "price": "0.51", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Little Nightmares I & II Bundle", "price": "2.11", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Little Nightmares II", "price": "1.41", "region": "A", "data": "11/1/", "status": "" },
  { "name": "MADiSON", "price": "2.33", "region": "T", "data": "11/1/", "status": "" },
  { "name": "MONOPOLY DEAL", "price": "0.03", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "MONOPOLY PLUS + MONOPOLY Madness", "price": "2.91", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "MY HERO ONE'S JUSTICE 2", "price": "6.62", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "MY HERO ONE'S JUSTICE 2 Deluxe Edition", "price": "9.71", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Mable & The Wood", "price": "0.12", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Madden NFL 19", "price": "29.11", "region": "C", "data": "12/30", "status": "" },
  { "name": "Madden NFL 22 Xbox One", "price": "11.00", "region": "A", "data": "12/31", "status": "" },
  { "name": "Madden NFL 22 Xbox Series X|S", "price": "12.80", "region": "A", "data": "12/31", "status": "" },
  { "name": "Madden NFL 23 Xbox One", "price": "14.63", "region": "A", "data": "12/31", "status": "" },
  { "name": "Madden NFL 23 Xbox Series X|S", "price": "17.14", "region": "A", "data": "12/31", "status": "" },
  { "name": "Madden NFL 24", "price": "17.14", "region": "A", "data": "12/1/", "status": "" },
  { "name": "Madden NFL 24 Deluxe Edition Xbox Series X|S & Xbox One", "price": "25.14", "region": "A", "data": "12/1/", "status": "" },
  { "name": "Maize", "price": "0.14", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Maneater", "price": "0.82", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Manual Samuel", "price": "0.03", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Maquette", "price": "0.32", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Marsupilami: Hoobadventure", "price": "2.86", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Marvel's Midnight Suns", "price": "8.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Marvel's Midnight Suns Digital+ Edition for Xbox One", "price": "10.29", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Marvel's Midnight Suns Digital+ Edition for Xbox Series X|S", "price": "10.29", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Marvel's Midnight Suns Enhanced Edition", "price": "9.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Marvel's Midnight Suns Legendary Edition for Xbox One", "price": "12.57", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Marvel's Midnight Suns Legendary Edition for Xbox Series X|S", "price": "12.57", "region": "A", "data": "11/1/", "status": "" },
  { "name": "May’s Mysteries: The Secret of Dragonville", "price": "0.18", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Meet Your Maker", "price": "5.01", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Megaparty: A Tootuff Adventure", "price": "0.18", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Memories of Mars", "price": "0.20", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Metal: Hellsinger (Xbox One)", "price": "0.61", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Metal: Hellsinger (Xbox Series X|S & PC)", "price": "0.82", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Metro 2033 Redux", "price": "0.11", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Metro Exodus", "price": "0.80", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Metro Saga Bundle", "price": "0.49", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Metro: Last Light Redux", "price": "0.11", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Miasma Chronicles", "price": "4.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Microsoft 365 Family", "price": "0.00", "region": "U", "data": "12/1/", "status": "" },
  { "name": "Microsoft 365 Personal", "price": "0.00", "region": "U", "data": "12/1/", "status": "" },
  { "name": "Mittelborg: City of Mages", "price": "0.09", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Monopoly Madness", "price": "2.14", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Monster Energy Supercross - Special Edition", "price": "0.86", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Monster Energy Supercross - The Official Videogame", "price": "0.57", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Moon Raider and Sweet Witches Bundle", "price": "0.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Moonshine Inc.", "price": "2.80", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Moonshine Inc. : Supporter Edition", "price": "3.50", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Morbid: The Seven Acolytes", "price": "0.20", "region": "A", "data": "11/1/", "status": "" },
  { "name": "MotoGP™21", "price": "1.29", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Motorbike Racing Bundle", "price": "1.71", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Moving Out", "price": "1.76", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Murder Diaries 2", "price": "0.24", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Murder Is Game Over", "price": "0.16", "region": "A", "data": "11/11", "status": "" },
  { "name": "My Fantastic Ranch", "price": "5.14", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "My Little Riding Champion", "price": "0.16", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "My Time At Portia", "price": "1.07", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "My Universe - Interior Designer", "price": "3.00", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "My Universe - My Baby", "price": "3.00", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "My Universe - School Teacher", "price": "3.00", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Mystik Belle", "price": "0.21", "region": "A", "data": "11/7/", "status": "" },
  { "name": "NASCAR Arcade Rush", "price": "22.90", "region": "I", "data": "11/7/", "status": "" },
  { "name": "NASCAR Arcade Rush Project-X Edition", "price": "23.68", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Narita Boy", "price": "0.69", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Necropolis", "price": "0.71", "region": "A", "data": "11/1/", "status": "" },
  { "name": "NeonPowerUp!", "price": "0.16", "region": "A", "data": "11/4/", "status": "" },
  { "name": "New Tales from the Borderlands: Deluxe Edition", "price": "10.00", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Ninja Warrior Epic Quest", "price": "0.10", "region": "A", "data": "5/31/", "status": "" },
  { "name": "No More Heroes 3 Xbox", "price": "4.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "No More Heroes 3 Xbox", "price": "2.00", "region": "T", "data": "11/7/", "status": "" },
  { "name": "No More Heroes 3 Xbox Digital Deluxe Edition", "price": "5.26", "region": "A", "data": "11/7/", "status": "" },
  { "name": "No More Heroes 3 Xbox Digital Deluxe Edition", "price": "2.40", "region": "T", "data": "11/7/", "status": "" },
  { "name": "No Place Like Home", "price": "0.82", "region": "A", "data": "11/7/", "status": "" },
  { "name": "No Son Of Mine", "price": "0.49", "region": "A", "data": "11/13", "status": "" },
  { "name": "ONE PUNCH MAN: A HERO NOBODY KNOWS Deluxe Edition", "price": "1.98", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Observer: System Redux", "price": "0.61", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Onimusha: Warlords", "price": "5.08", "region": "B", "data": "11/1/", "status": "" },
  { "name": "Open Country", "price": "0.69", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Outbreak: Contagious Memories", "price": "0.31", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Outbreak: Lost Hope Definitive Collection", "price": "0.26", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Outbreak: The New Nightmare Definitive Collection", "price": "0.82", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Outbreak: The Nightmare Chronicles Definitive Collection", "price": "0.82", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Outward: Definitive Edition", "price": "1.43", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Outward: The Adventurer Bundle", "price": "0.41", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Overcooked: Gourmet Edition", "price": "0.17", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Oxide Room 104", "price": "1.01", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "PAYDAY 2: CRIMEWAVE EDITION", "price": "0.11", "region": "A", "data": "11/7/", "status": "" },
  { "name": "PGA TOUR 2K23 Deluxe Edition", "price": "7.86", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "PROJECT ZERO: Mask of the Lunar Eclipse", "price": "12.35", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Perfect Ninja Painter", "price": "0.18", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Pillar by Michael Hicks and Gonçalo Antunes", "price": "1.23", "region": "I", "data": "11/7/", "status": "" },
  { "name": "Portal Knights", "price": "0.17", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Prey", "price": "1.93", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Prey®: Digital Deluxe Edition", "price": "2.52", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Project Highrise: Architect's Edition", "price": "0.25", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Quiplash", "price": "0.14", "region": "A", "data": "11/7/", "status": "" },
  { "name": "RACCOON CITY EDITION", "price": "10.60", "region": "T", "data": "11/1/", "status": "" },
  { "name": "RAGE 2", "price": "2.52", "region": "T", "data": "11/1/", "status": "" },
  { "name": "RESIDENT EVIL 2", "price": "6.64", "region": "J", "data": "11/1/", "status": "" },
  { "name": "RESIDENT EVIL 2 Deluxe Edition", "price": "8.30", "region": "J", "data": "11/1/", "status": "" },
  { "name": "RESIDENT EVIL 3", "price": "6.64", "region": "J", "data": "11/1/", "status": "" },
  { "name": "RESIDENT EVIL 7 biohazard", "price": "5.30", "region": "J", "data": "11/1/", "status": "" },
  { "name": "RESIDENT EVIL 7 biohazard Gold Edition", "price": "11.31", "region": "T", "data": "11/1/", "status": "" },
  { "name": "RIDE 3", "price": "1.29", "region": "A", "data": "11/7/", "status": "" },
  { "name": "RIDE 3 - Gold Edition", "price": "2.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "RIOT: Civil Unrest", "price": "0.11", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Rabbids Invasion : The Interactive TV Show", "price": "0.11", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Rabbids®: Party of Legends", "price": "3.71", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Railway Empire", "price": "0.41", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Raji: An Ancient Epiс", "price": "1.67", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Ravenous Devils", "price": "0.10", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Rayman Legends", "price": "0.54", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Red Dead Redemption & Red Dead Redemption 2 Bundle", "price": "9.95", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Red Faction Guerrilla Re-Mars-tered", "price": "0.13", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Regular Factory: Escape Room", "price": "0.32", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Repentant", "price": "0.32", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Resident Evil", "price": "3.07", "region": "B", "data": "11/1/", "status": "" },
  { "name": "Resident Evil 0", "price": "3.07", "region": "B", "data": "11/1/", "status": "" },
  { "name": "Resident Evil 4", "price": "15.95", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Resident Evil 4 Deluxe Edition", "price": "19.44", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Resident Evil 5", "price": "5.63", "region": "S", "data": "11/1/", "status": "" },
  { "name": "Resident Evil 6", "price": "5.63", "region": "S", "data": "11/1/", "status": "" },
  { "name": "Resident Evil 7 Gold Edition & Village Gold Edition", "price": "22.61", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Resident Evil Revelations", "price": "5.68", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Resident Evil Revelations 1 & 2 Bundle", "price": "11.31", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Resident Evil Revelations 2 Deluxe Edition", "price": "8.19", "region": "C", "data": "11/1/", "status": "" },
  { "name": "Resident Evil Triple Pack", "price": "13.21", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Resident Evil Village", "price": "11.31", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Resident Evil Village Gold Edition", "price": "14.14", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Resident Evil: Deluxe Origins Bundle", "price": "6.41", "region": "B", "data": "11/1/", "status": "" },
  { "name": "Return to Monkey Island", "price": "3.03", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "RiMS Racing - European Manufacturers Deluxe Edition Xbox One", "price": "2.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "RiMS Racing - European Manufacturers Deluxe Edition Xbox Series X|S", "price": "2.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "RiMS Racing - Japanese Manufacturers Deluxe Edition Xbox One", "price": "2.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "RiMS Racing - Japanese Manufacturers Deluxe Edition Xbox Series X|S", "price": "2.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "RiMS Racing Xbox One", "price": "1.60", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "RiMS Racing Xbox Series X|S", "price": "1.60", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Risk: Urban Assault", "price": "0.17", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Road 96", "price": "0.75", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Rogue Spirit", "price": "3.43", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Rugby 22 Xbox One", "price": "1.93", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Rugby 22 Xbox Series X|S", "price": "1.93", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Rune Factory 4 Special", "price": "1.50", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Russian Subway Dogs", "price": "1.78", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "SCARLET NEXUS", "price": "2.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "SCARLET NEXUS Deluxe Edition", "price": "2.29", "region": "A", "data": "11/7/", "status": "" },
  { "name": "SCARLET NEXUS Ultimate Edition", "price": "2.86", "region": "A", "data": "11/1/", "status": "" },
  { "name": "SILT", "price": "0.34", "region": "A", "data": "11/1/", "status": "" },
  { "name": "STAR WARS Jedi: Fallen Order™", "price": "3.66", "region": "A", "data": "12/31", "status": "" },
  { "name": "STAR WARS Jedi: Fallen Order™ Deluxe Edition", "price": "4.88", "region": "A", "data": "1/1/2", "status": "" },
  { "name": "STAR WARS™ Episode I Racer", "price": "0.31", "region": "A", "data": "11/7/", "status": "" },
  { "name": "STORY OF SEASONS: A Wonderful Life", "price": "15.91", "region": "T", "data": "11/7/", "status": "" },
  { "name": "STORY OF SEASONS: A Wonderful Life", "price": "14.57", "region": "A", "data": "11/7/", "status": "" },
  { "name": "STORY OF SEASONS: Friends of Mineral Town - Digital Edition", "price": "0.66", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Saints Row IV: Re-Elected", "price": "0.17", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Saints Row Platinum Edition", "price": "9.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Saints Row The Third Remastered", "price": "1.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Scars Above", "price": "6.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Scott Pilgrim vs. The World™: The Game – Complete Edition", "price": "0.80", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Scrabble", "price": "5.42", "region": "C", "data": "11/7/", "status": "GOLD" },
  { "name": "Scribblenauts Mega Pack", "price": "0.56", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Secret Neighbor", "price": "0.20", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Serial Cleaners", "price": "1.37", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Session: Skate Sim", "price": "1.02", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Shadowblade Odyssey", "price": "0.04", "region": "A", "data": "11/8/", "status": "" },
  { "name": "Shadows: Awakening", "price": "0.40", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Sherlock Holmes: Crimes and Punishments + Sherlock Holmes...", "price": "2.19", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Shining Resonance Refrain", "price": "1.33", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Sid Meier’s Civilization® VI Anthology", "price": "7.00", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Sid Meier’s Civilization® VI Platinum Edition", "price": "3.57", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Silver Nornir", "price": "0.40", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Skeljump", "price": "0.16", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Skull Island: Rise of Kong", "price": "20.89", "region": "I", "data": "11/1/", "status": "" },
  { "name": "Skull Island: Rise of Kong - Colossal Edition", "price": "26.17", "region": "I", "data": "11/1/", "status": "" },
  { "name": "Skyrim Anniversary Edition + Fallout 4 G.O.T.Y Bundle", "price": "9.33", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Slaycation Paradise", "price": "0.28", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Sparkle Bundle", "price": "0.36", "region": "A", "data": "12/31", "status": "" },
  { "name": "SpellForce III Reforced", "price": "2.31", "region": "A", "data": "11/1/", "status": "" },
  { "name": "SpellForce: Conquest of Eo", "price": "8.48", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Starlink: Battle for Atlas™", "price": "0.69", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Steel Rats™", "price": "0.04", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Steelrising - Standard Edition", "price": "4.46", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Stellaris: Console Edition - Deluxe Edition", "price": "0.63", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Stranded Sails - Explorers of the Cursed Islands", "price": "0.25", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Strategic Mind: Spirit of Liberty", "price": "5.40", "region": "A", "data": "11/10", "status": "" },
  { "name": "Strategic Mind: The Pacific", "price": "0.61", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Subnautica", "price": "0.28", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Sudden Strike 4 - Complete Collection", "price": "0.82", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Super Mega Baseball™ 4", "price": "12.57", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Super Monkey Ball Banana Mania Digital Deluxe Edition", "price": "5.09", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Super Pixel Kid", "price": "0.04", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Super Retro Charge", "price": "0.31", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Swapshot (Xbox & PC)", "price": "2.58", "region": "I", "data": "11/9/", "status": "" },
  { "name": "Sweet Witches", "price": "0.08", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Syberia - The World Before", "price": "1.02", "region": "A", "data": "11/7/", "status": "" },
  { "name": "THE HOUSE OF THE DEAD: Remake", "price": "0.34", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "TRIVIAL PURSUIT Live! 2", "price": "1.43", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Tales of ARISE + SCARLET NEXUS バンドル", "price": "28.80", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Tanks Bundle", "price": "0.43", "region": "A", "data": "11/5/", "status": "" },
  { "name": "Team Sonic Racing™", "price": "3.53", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Tennis World Tour 2", "price": "1.71", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Tennis World Tour 2 - Complete Edition Xbox Series X|S", "price": "0.41", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Terraria", "price": "0.28", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Addams Family: Mansion Mayhem", "price": "2.91", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Beast Inside (Console Version)", "price": "0.51", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Bridge", "price": "0.07", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Callisto Protocol™ for Xbox One – Digital Deluxe Edition", "price": "5.71", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Callisto Protocol™ for Xbox Series X|S – Digital Delu...", "price": "7.43", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Chant", "price": "7.34", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Dark Pictures Anthology House of Ashes", "price": "1.62", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Dark Pictures Anthology: Little Hope", "price": "3.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Dark Pictures Anthology: Man Of Medan", "price": "3.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Dark Pictures Anthology: Season One", "price": "13.57", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Dark Pictures Anthology: The Devil in Me", "price": "5.64", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Elder Scrolls Online Collection: Necrom", "price": "12.37", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Elder Scrolls V: Skyrim Special Edition", "price": "3.09", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Evil Within", "price": "1.58", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Evil Within (PC)", "price": "0.64", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Evil Within Digital Bundle", "price": "0.89", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Evil Within® 2", "price": "1.27", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Galactic Junkers", "price": "0.86", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "The Inner World - The Last Wind Monk", "price": "0.08", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Jackbox Party Pack 3", "price": "0.43", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Jackbox Party Quadpack", "price": "1.61", "region": "A", "data": "12/31", "status": "" },
  { "name": "The Jackbox Party Starter", "price": "0.41", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "The Last Kids on Earth and the Staff of Doom", "price": "2.57", "region": "E", "data": "11/1/", "status": "" },
  { "name": "The Last Oricru", "price": "3.17", "region": "T", "data": "11/1/", "status": "" },
  { "name": "The Long Reach", "price": "0.06", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Medium", "price": "1.02", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Mummy Demastered", "price": "0.28", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Myth Seekers: The Legacy of Vulkan (Xbox Version)", "price": "2.28", "region": "A", "data": "11/6/", "status": "" },
  { "name": "The Outer Worlds", "price": "5.57", "region": "E", "data": "11/1/", "status": "" },
  { "name": "The Path of Motus", "price": "2.29", "region": "B", "data": "11/7/", "status": "GOLD" },
  { "name": "The Quarry - Deluxe Edition", "price": "5.71", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Quarry for Xbox One", "price": "4.29", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Quarry for Xbox Series X|S", "price": "5.00", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Sinking City", "price": "0.31", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Sinking City Xbox Series X|S Deluxe Edition", "price": "2.19", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Smurfs - Mission Vileaf", "price": "2.84", "region": "E", "data": "11/7/", "status": "GOLD" },
  { "name": "The Talos Principle 2", "price": "5.40", "region": "A", "data": "11/2/", "status": "" },
  { "name": "The Texas Chain Saw Massacre", "price": "8.03", "region": "E", "data": "11/8/", "status": "" },
  { "name": "The Unicorn Princess", "price": "0.08", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "The Walking Dead: A New Frontier - The Complete Season (Episodes 1-5)", "price": "0.16", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Walking Dead: Michonne - The Complete Season", "price": "0.11", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Walking Dead: Season Two", "price": "0.16", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Walking Dead: The Complete First Season", "price": "0.16", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Walking Dead: The Final Season - The Complete Season", "price": "0.14", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Walking Dead: The Telltale Definitive Series", "price": "0.51", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Wild Eight", "price": "0.12", "region": "A", "data": "11/7/", "status": "" },
  { "name": "The Witcher 3: Wild Hunt", "price": "2.28", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Witcher 3: Wild Hunt – Complete Edition", "price": "3.77", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Wolf Among Us", "price": "0.26", "region": "A", "data": "11/1/", "status": "" },
  { "name": "The Yakuza Remastered Collection", "price": "2.55", "region": "T", "data": "11/7/", "status": "" },
  { "name": "The Yakuza Remastered Collection for Windows 10", "price": "2.55", "region": "T", "data": "11/7/", "status": "" },
  { "name": "There Is No Light", "price": "3.04", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Tiny Tina's Assault on Dragon Keep: A Wonderlands One-sho...", "price": "1.25", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Tom Clancy's The Division™ Gold Edition", "price": "1.41", "region": "T", "data": "11/7/", "status": "GOLD" },
  { "name": "Tomb Raider I-III Remastered Starring Lara Croft", "price": "1.10", "region": "A", "data": "2/13/", "status": "" },
  { "name": "Trackmania® Turbo", "price": "0.23", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Train Life - Orient-Express Train Edition", "price": "0.66", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Transport Fever 2: Console Edition - Deluxe", "price": "14.00", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Trials® Rising - Digital Gold Edition", "price": "1.28", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Tribes of Midgard", "price": "1.34", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Tribes of Midgard Deluxe Edition", "price": "2.01", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Tunche", "price": "0.32", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Twin Mirror", "price": "0.86", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Underworld Ascendant", "price": "0.31", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Unheard - Voices of Crime Edition", "price": "0.74", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Unit 4: Couch Attack Bundle", "price": "0.39", "region": "A", "data": "12/30", "status": "" },
  { "name": "Unravel Two", "price": "0.36", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Unturned", "price": "1.21", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Vampire Survivors", "price": "0.64", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Vampire: The Masquerade - Swansong PRIMOGEN EDITION", "price": "3.71", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Vermintide - Digital Value Pack", "price": "1.14", "region": "A", "data": "3/7/2", "status": "" },
  { "name": "Vikings - Wolves of Midgard", "price": "0.43", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Virginia", "price": "0.10", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Voodoo Vince: Remastered", "price": "0.15", "region": "A", "data": "11/1/", "status": "" },
  { "name": "WRC 10 FIA World Rally Championship Xbox One", "price": "1.20", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "WRC 10 FIA World Rally Championship Xbox Series X|S", "price": "1.50", "region": "A", "data": "11/7/", "status": "" },
  { "name": "WRC Collection FIA World Rally Championship", "price": "1.82", "region": "A", "data": "8/31/", "status": "" },
  { "name": "Warhammer 40,000: Inquisitor - Martyr Ultimate Edition", "price": "0.82", "region": "A", "data": "11/7/", "status": "" },
  { "name": "Warhammer: Chaosbane Slayer Edition Xbox One", "price": "0.16", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Warhammer: Chaosbane Slayer Edition Xbox Series X|S", "price": "0.25", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Wasteland 3", "price": "0.86", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Werewolf: The Apocalypse - Earthblood Xbox One", "price": "0.97", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Werewolf: The Apocalypse - Earthblood Xbox Series X|S", "price": "0.97", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Wheel Of Fortune®", "price": "0.30", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Witchy Life Story", "price": "0.69", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Wizardry School: Escape Room", "price": "0.36", "region": "A", "data": "11/1/", "status": "" },
  { "name": "Wolfenstein: The New Order", "price": "0.61", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Wolfenstein: The Old Blood", "price": "0.51", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Wolfenstein: Youngblood", "price": "1.52", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Wolfenstein: Youngblood Deluxe Edition", "price": "1.93", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Wolfenstein® II: The New Colossus™ Digital Deluxe Edition", "price": "1.59", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Wolfenstein®: The Two-Pack", "price": "1.40", "region": "T", "data": "11/1/", "status": "" },
  { "name": "Woodle Tree 2: Deluxe+", "price": "0.05", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "World Of Solitaire", "price": "0.28", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "World War Z", "price": "0.61", "region": "A", "data": "11/2/", "status": "" },
  { "name": "Worldless", "price": "3.60", "region": "A", "data": "11/21", "status": "" },
  { "name": "X-Force Genesis PC Edition", "price": "0.17", "region": "A", "data": "11/10", "status": "" },
  { "name": "Yakuza 0", "price": "0.64", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza 0 for Windows 10", "price": "0.64", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza 6: The Song of Life", "price": "0.64", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza 6: The Song of Life for Windows 10", "price": "0.64", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza Kiwami", "price": "0.64", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza Kiwami 2", "price": "1.33", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza Kiwami 2 for Windows 10", "price": "1.33", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Yakuza Kiwami for Windows 10", "price": "0.64", "region": "T", "data": "11/7/", "status": "" },
  { "name": "Zombies Ate My Neighbors and Ghoul Patrol", "price": "5.04", "region": "I", "data": "11/1/", "status": "" },
  { "name": "Zorro The Chronicles Xbox One", "price": "3.09", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "Zorro The Chronicles Xbox Series X|S", "price": "3.09", "region": "A", "data": "11/7/", "status": "GOLD" },
  { "name": "orbit.industries", "price": "0.49", "region": "A", "data": "11/7/", "status": "" },
  { "name": "resident evil 4", "price": "5.63", "region": "S", "data": "11/1/", "status": "" }

]



console.log(arr.length);
const sortArr = arr.sort(function (a, b) {
  if (a.name > b.name) {
    return 1;
  }
  if (a.name < b.name) {
    return -1;
  }
  return 0;
});

function floor(price) {
  let enterPrice = Number(price)
  const lastNum = Number(enterPrice.toString().split('').pop())

  switch (lastNum) {
    case 1:
      enterPrice += 4
      break;
    case 2:
      enterPrice += 3
      break;
    case 3:
      enterPrice += 2
      break;
    case 4:
      enterPrice += 1
      break;
    case 6:
      enterPrice += 4
      break;
    case 7:
      enterPrice += 3
      break;
    case 8:
      enterPrice += 2
      break;
    case 9:
      enterPrice += 1
      break;
    default:
      enterPrice
      break;
  }
  return enterPrice;
}

function result() {
  const value = Number(input.value) + .1
  const res = value * usd
  const finishRes = res + resSwitсh(input.value)
  output.innerHTML = floor(finishRes.toFixed())
}

function resultFromList(price) {
  const value = Number(price) + .1
  const res = value * usd + 40
  const finishRes = res + resSwitсh(price)
  return floor(finishRes.toFixed())
}

function resSwitсh(value) {
  let a;
  if (value <= 1) {
    a = 60
  } else if (value > 1 && value <= 5) {
    a = 75
  } else if (value > 5 && value <= 10) {
    a = 90
  } else if (value > 10 && value <= 15) {
    a = 125
  } else if (value > 15 && value <= 20) {
    a = 145
  } else if (value > 20 && value <= 25) {
    a = 190
  } else if (value > 25) {
    a = 210
  }
  return a
}

input.oninput = result


sortArr.map((a) => {
  const item = document.createElement('li')
  const arrData = a.data.split('/').reverse('').join('/')
  let res;
  let flag;
  if (a.region == 'A') {
    res = resultFromList(a.price)
    flag = "🇦🇷"
  } else if (a.region == 'T') {
    res = resultFromList(a.price)
    flag = "🇹🇷"
  } else {
    res = 'Уточнить стоимость в ЛС'
  }

  item.innerHTML = res == 'Уточнить стоимость в ЛС' ? `${a.name}: ${res} до:${arrData}` : `${a.name}:${res}&#8381; ${flag}  до:${arrData}${a.status}`
  // &#8381; ${ flag } до:${ arrData }${ a.status }
  list.append(item)
})
// 
function showMenu() {
  showBtn.classList.add('active')
  list.classList.add('active');
  showBtn.innerHTML = 'Скрыть Список'
  showBtn.style.background = 'red'

}

function hiddenMenu() {
  showBtn.classList.remove('active')
  list.classList.remove('active');
  showBtn.innerHTML = 'Показать Список'
  showBtn.style.background = 'greenyellow'
}
