const input = document.querySelector('.input');
const output = document.querySelector('.output-res');
const list = document.querySelector('.list')
const showBtn = document.querySelector('.show')


showBtn.addEventListener('click', () => {
  showBtn.classList.contains('active') ?
    hiddenMenu() : showMenu()
})

let usd = 84;

const arr = [
  { "name": "39 Days to Mars", "price": 1.78 },
  { "name": "A Gummy's Life", "price": 1.03 },
  { "name": "AQUA KITTY UDX: Xbox One Ultra Edition", "price": 0.87 },
  { "name": "AVICII Invector", "price": 0.37 },
  { "name": "AVICII Invector: Encore Edition", "price": 0.67 },
  { "name": "Absolver", "price": 0.31 },
  { "name": "Aeon Must Die!", "price": 3.52 },
  { "name": "Aery - Sky Castle", "price": 0.48 },
  { "name": "Afterglitch", "price": 1.0 },
  { "name": "Ages of Mages: the last keeper", "price": 0.45 },
  { "name": "Akane", "price": 0.11 },
  { "name": "Alphadia Genesis 1 & 2", "price": 0.74 },
  { "name": "AngerForce:Reloaded", "price": 0.21 },
  { "name": "Ape Out", "price": 0.28 },
  { "name": "Arcadegeddon", "price": 2.94 },
  { "name": "Arkham Horror: Mother’s Embrace", "price": 0.59 },
  { "name": "Asdivine Dios", "price": 0.55 },
  { "name": "Asdivine Hearts I & II", "price": 0.74 },
  { "name": "Assassin's Creed® Odyssey - ULTIMATE EDITION", "price": 5.82 },
  { "name": "Assassin's Creed® Syndicate Gold Edition", "price": 2.78 },
  { "name": "Assassin's Creed® Valhalla Deluxe Edition", "price": 8.54 },
  { "name": "Assassin's Creed® Valhalla Ragnarök Edition", "price": 11.13 },
  { "name": "Assassin’s Creed® Rogue Remastered", "price": 1.42 },
  { "name": "Assassin’s Creed® Valhalla + Immortals Fenyx Rising™ Bundle", "price": 8.41 },
  { "name": "Assassin’s Creed® Valhalla + Watch Dogs®: Legion Bundle", "price": 8.41 },
  { "name": "Awarded Platformer Bundle", "price": 0.85 },
  { "name": "Awkward", "price": 0.77 },
  { "name": "BROK the InvestiGator", "price": 1.49 },
  { "name": "Battle Axe", "price": 0.56 },
  { "name": "Beat Me!", "price": 0.29 },
  { "name": "Big Rumble Boxing: Creed Champions", "price": 5.81 },
  { "name": "BioShock: The Collection", "price": 2.52 },
  { "name": "Biped", "price": 0.44 },
  { "name": "Bite the Bullet", "price": 0.22 },
  { "name": "Black Book", "price": 0.93 },
  { "name": "Blazing Chrome", "price": 0.51 },
  { "name": "Bleed Complete Bundle", "price": 0.22 },
  { "name": "Blightbound", "price": 0.74 },
  { "name": "Bloodstained: Ritual of the Night", "price": 3.32 },
  { "name": "Bloody Zombies", "price": 0.17 },
  { "name": "Bloons TD 5", "price": 0.39 },
  { "name": "Boggle", "price": 0.19 },
  { "name": "Bomber Crew Deluxe Edition", "price": 0.93 },
  { "name": "Boom Ball 2 for Kinect", "price": 0.13 },
  { "name": "Boom Ball 3 for Kinect", "price": 0.15 },
  { "name": "Boomerang Fu", "price": 0.78 },
  { "name": "Borderlands 3", "price": 2.14 },
  { "name": "Borderlands 3: Super Deluxe Edition", "price": 4.53 },
  { "name": "Borderlands Legendary Collection", "price": 5.91 },
  { "name": "Borderlands: Game of the Year Edition", "price": 2.4 },
  { "name": "Brawlout Deluxe Edition", "price": 0.54 },
  { "name": "Brawlout Standard Edition", "price": 0.36 },
  { "name": "Breathedge", "price": 0.74 },
  { "name": "Bridge Constructor Bundle", "price": 0.21 },
  { "name": "Bridge Constructor Stunts", "price": 0.1 },
  { "name": "Broforce", "price": 0.28 },
  { "name": "Bundle: South Park™ : The Stick of Truth™ + The Fractured...", "price": 5.55 },
  { "name": "Butterfly", "price": 0.24 },
  { "name": "Butterfly 2", "price": 0.24 },
  { "name": "CATAN® - Console Edition Deluxe", "price": 5.43 },
  { "name": "CUBERS: ARENA", "price": 0.44 },
  { "name": "Call of Duty: Ghosts Digital Hardened Edition", "price": 1.98 },
  { "name": "Call of Duty®: Advanced Warfare Digital Pro Edition", "price": 1.98 },
  { "name": "Call of Duty®: Black Ops 4", "price": 7.62 },
  { "name": "Call of Duty®: Black Ops 4 - Digital Deluxe", "price": 17.0 },
  { "name": "Call of Duty®: Black Ops Cold War", "price": 7.62 },
  { "name": "Call of Duty®: Black Ops Cold War - Cross-Gen Bundle", "price": 13.25 },
  { "name": "Call of Duty®: Black Ops III - Zombies Chronicles Edition", "price": 3.07 },
  { "name": "Call of Duty®: Infinite Warfare - Digital Legacy Edition", "price": 4.66 },
  { "name": "Call of Duty®: Modern Warfare® - Digital Standard Edition", "price": 7.62 },
  { "name": "Call of Duty®: Modern Warfare® II - Cross-Gen Bundle", "price": 27.15 },
  { "name": "Call of Duty®: Vanguard - Cross-Gen Bundle", "price": 15.87 },
  { "name": "Call of Duty®: Vanguard - Standard Edition", "price": 13.22 },
  { "name": "Call of Duty®: WWII - Digital Deluxe", "price": 9.96 },
  { "name": "Can't Drive This", "price": 0.96 },
  { "name": "Cannon Brawl", "price": 0.15 },
  { "name": "Car Mechanic Simulator Classic", "price": 0.63 },
  { "name": "Carnival Games®", "price": 1.54 },
  { "name": "Carrion", "price": 0.59 },
  { "name": "Castle Crashers Remastered", "price": 1.29 },
  { "name": "Castle on the Coast", "price": 0.83 },
  { "name": "CastleStorm - Definitive Edition", "price": 0.23 },
  { "name": "Cave Bad", "price": 0.14 },
  { "name": "Caveman Warriors", "price": 0.19 },
  { "name": "Chess Ultra", "price": 0.22 },
  { "name": "Chroma Quaternion", "price": 0.66 },
  { "name": "Circuit Breakers", "price": 0.1 },
  { "name": "City of Brass", "price": 0.1 },
  { "name": "Clan N", "price": 0.44 },
  { "name": "Clumsy Rush", "price": 0.24 },
  { "name": "Colossus Down", "price": 0.4 },
  { "name": "Colt Canyon", "price": 0.28 },
  { "name": "Conan Chop Chop", "price": 1.81 },
  { "name": "Cook, Serve, Delicious! 2!!", "price": 0.24 },
  { "name": "Cook, Serve, Delicious! 3?!", "price": 0.51 },
  { "name": "Couch Multiplayer Bundle: Genetic Disaster, Super Cyborg ...", "price": 0.8 },
  { "name": "Crash™ Team Racing Nitro-Fueled - Nitros Oxide Edition", "price": 5.44 },
  { "name": "Cube Farmer", "price": 0.29 },
  { "name": "Cult of the Lamb", "price": 2.83 },
  { "name": "Cult of the Lamb: Cultist Edition", "price": 3.38 },
  { "name": "Cuphead", "price": 1.03 },
  { "name": "Cuphead & The Delicious Last Course", "price": 2.91 },
  { "name": "Cyber Pool", "price": 0.09 },
  { "name": "CyberHeroes Arena DX", "price": 0.29 },
  { "name": "Cyberpunk 2077", "price": 10.35 },
  { "name": "Cymatically Muffed", "price": 0.69 },
  { "name": "DEMON'S TILT", "price": 0.44 },
  { "name": "DRAGON BALL FIGHTERZ - FighterZ Edition", "price": 1.75 },
  { "name": "DRAGON BALL XENOVERSE 2", "price": 1.4 },
  { "name": "DRAGON BALL: THE BREAKERS Special Edition", "price": 8.23 },
  { "name": "Danger Scavenger", "price": 0.07 },
  { "name": "Dark Burial: Enhanced Edition", "price": 0.29 },
  { "name": "DayZ", "price": 2.22 },
  { "name": "Dead End Job", "price": 0.25 },
  { "name": "Death's Door [Win10]", "price": 0.74 },
  { "name": "Death's Door [Xbox]", "price": 0.74 },
  { "name": "Demolish & Build", "price": 0.74 },
  { "name": "Demon Slayer -Kimetsu no Yaiba- The Hinokami Chronicles D...", "price": 9.32 },
  { "name": "Demon's Tier+", "price": 0.15 },
  { "name": "Demoniaca: Everlasting Night", "price": 0.55 },
  { "name": "Deployment", "price": 0.29 },
  { "name": "Desert Child", "price": 0.22 },
  { "name": "Diablo III: Eternal Collection", "price": 4.11 },
  { "name": "Diablo® II: Resurrected™", "price": 3.83 },
  { "name": "Diablo® Prime Evil Collection", "price": 5.78 },
  { "name": "Diablo® Prime Evil Upgrade", "price": 4.8 },
  { "name": "Digimon Survive", "price": 15.55 },
  { "name": "Disc Room", "price": 0.55 },
  { "name": "Discolored", "price": 0.4 },
  { "name": "Discovery Tour: Viking Age", "price": 6.0 },
  { "name": "Disney Dreamlight Valley", "price": 6.5 },
  { "name": "Disney Dreamlight Valley — Ultimate Edition", "price": 14.2 },
  { "name": "Don't Starve Together: Console Edition", "price": 0.31 },
  { "name": "Door Kickers: Action Squad", "price": 0.22 },
  { "name": "Dragon Ball Xenoverse + Season Pass", "price": 0.81 },
  { "name": "Droid Trivia", "price": 2.04 },
  { "name": "Drone Gladiator", "price": 0.2 },
  { "name": "EA SPORTS™ FIFA 23 Standard Edition Xbox One", "price": 11.13 },
  { "name": "EA SPORTS™ FIFA 23 Standard Edition Xbox Series X|S", "price": 12.72 },
  { "name": "Enter The Gungeon", "price": 0.44 },
  { "name": "Escape Academy", "price": 4.42 },
  { "name": "Escape Dead Island", "price": 0.2 },
  { "name": "Eternal Hope", "price": 0.31 },
  { "name": "Exit the Gungeon", "price": 0.37 },
  { "name": "FIFA 22 Xbox One", "price": 21.2 },
  { "name": "FIFA 22 Xbox Series X|S", "price": 23.74 },
  { "name": "FOCUS INDIES BUNDLE - Curse of the Dead Gods + Shady Part of Me + Aeon Must Die!", "price": 8.06 },
  { "name": "FROGUN", "price": 0.78 },
  { "name": "Fantasy Dash", "price": 0.08 },
  { "name": "Far Cry® 3 Blood Dragon Classic Edition", "price": 3.88 },
  { "name": "Far Cry® 3 Classic Edition", "price": 0.77 },
  { "name": "Far Cry® 5 + Far Cry® New Dawn Deluxe Edition Bundle", "price": 4.53 },
  { "name": "Far Cry® 6 Game of the Year Edition", "price": 17.09 },
  { "name": "Fernz Gate", "price": 0.55 },
  { "name": "Fight'N Rage", "price": 0.51 },
  { "name": "Final Vendetta", "price": 3.44 },
  { "name": "Flat Heroes", "price": 0.77 },
  { "name": "Flewfie's Adventure", "price": 0.35 },
  { "name": "For Honor® Complete Edition", "price": 6.47 },
  { "name": "Fueled Up", "price": 0.88 },
  { "name": "Full Metal Furies", "price": 0.29 },
  { "name": "GONNER2", "price": 0.29 },
  { "name": "GRIP Digital Deluxe", "price": 0.37 },
  { "name": "GRIS", "price": 2.45 },
  { "name": "Galacide", "price": 0.55 },
  { "name": "Gato Roboto", "price": 0.15 },
  { "name": "Geometric Sniper - Blood in Paris", "price": 0.18 },
  { "name": "Ghost Sync", "price": 0.66 },
  { "name": "Giraffe and Annika（ジラフとアンニカ）", "price": 0.89 },
  { "name": "Glam's Incredible Run: Escape from Dukha", "price": 0.11 },
  { "name": "Go! Go! PogoGirl", "price": 0.29 },
  { "name": "Goat Simulator 3", "price": 6.21 },
  { "name": "Golazo!", "price": 0.22 },
  { "name": "Golazo! 2", "price": 2.95 },
  { "name": "Grand Theft Auto V", "price": 10.35 },
  { "name": "Grand Theft Auto V: Premium Edition", "price": 4.01 },
  { "name": "Grand Theft Auto: The Trilogy – The Definitive Edition", "price": 14.02 },
  { "name": "Grapple Dog", "price": 0.55 },
  { "name": "Gravity Heroes", "price": 0.55 },
  { "name": "GreedFall - Gold Edition (Windows 10)", "price": 3.42 },
  { "name": "Green Hell", "price": 1.3 },
  { "name": "Guacamelee! 2", "price": 0.37 },
  { "name": "Guacamelee! Super Turbo Championship Edition", "price": 0.18 },
  { "name": "Guilt Battle Arena", "price": 0.07 },
  { "name": "Guns, Gore and Cannoli", "price": 0.21 },
  { "name": "Guns, Gore and Cannoli 2", "price": 0.33 },
  { "name": "HOT WHEELS UNLEASHED™", "price": 2.59 },
  { "name": "HOT WHEELS UNLEASHED™ - Game Of The Year Edition", "price": 4.14 },
  { "name": "HOT WHEELS UNLEASHED™ - Game Of The Year Edition - Xbox S...", "price": 4.14 },
  { "name": "HOT WHEELS UNLEASHED™ - Xbox Series X|S", "price": 2.59 },
  { "name": "Hatsune Miku Jigsaw Puzzle", "price": 8.95 },
  { "name": "Hatsune Miku Logic Paint S", "price": 8.95 },
  { "name": "Haven", "price": 0.93 },
  { "name": "Help Will Come Tomorrow", "price": 0.29 },
  { "name": "Hexagroove: Tactical DJ", "price": 7.61 },
  { "name": "Historical Trilogy", "price": 1.11 },
  { "name": "Horizon Chase Turbo", "price": 0.61 },
  { "name": "Horror Bundle : Paratopic + Fatum Betula", "price": 0.59 },
  { "name": "Hotline Miami Collection", "price": 0.46 },
  { "name": "Hotshot Racing", "price": 0.29 },
  { "name": "Hunt Ducks 4", "price": 0.08 },
  { "name": "Hunt: Showdown", "price": 2.86 },
  { "name": "Hunt: Showdown - Deluxe Edition", "price": 2.25 },
  { "name": "Hunt: Showdown - Gold Edition", "price": 2.62 },
  { "name": "Hyper Gunsport", "price": 1.49 },
  { "name": "Hyper Shapes", "price": 0.33 },
  { "name": "Hyposphere: Rebirth", "price": 0.22 },
  { "name": "I Hate Running Backwards", "price": 0.15 },
  { "name": "Infinite Minigolf", "price": 0.31 },
  { "name": "Inukari - Chase of Deception", "price": 0.21 },
  { "name": "Iron Crypticle", "price": 0.14 },
  { "name": "Jack Move", "price": 4.12 },
  { "name": "Jelly Brawl", "price": 0.37 },
  { "name": "Jeopardy!", "price": 0.39 },
  { "name": "Joy Ball Adventure", "price": 0.15 },
  { "name": "Just Die Already", "price": 0.46 },
  { "name": "Just Shapes & Beats", "price": 1.03 },
  { "name": "Katana Zero XB1", "price": 0.66 },
  { "name": "Keep Talking and Nobody Explodes", "price": 0.55 },
  { "name": "Kerbal Space Program Enhanced Edition", "price": 2.34 },
  { "name": "Kingdom Two Crowns", "price": 0.36 },
  { "name": "Kitaria Fables", "price": 0.81 },
  { "name": "Knights & Guns", "price": 0.87 },
  { "name": "Knights and Bikes", "price": 0.74 },
  { "name": "L.A. Noire", "price": 3.62 },
  { "name": "Lanternium", "price": 0.52 },
  { "name": "Levelhead", "price": 1.03 },
  { "name": "Life of Fly", "price": 0.66 },
  { "name": "Light & Dark Bundle", "price": 1.16 },
  { "name": "Little Mage Adventure", "price": 0.08 },
  { "name": "Little Mouse's Encyclopedia + Clumsy Rush", "price": 0.28 },
  { "name": "Little Mouse's Encyclopedia + Cyber Protocol", "price": 0.18 },
  { "name": "Little Triangle", "price": 0.66 },
  { "name": "Lost Judgment Digital Deluxe Edition", "price": 7.45 },
  { "name": "Lost Sea", "price": 0.08 },
  { "name": "Lovers in a Dangerous Spacetime", "price": 0.39 },
  { "name": "Lunch A Palooza", "price": 0.59 },
  { "name": "MINIT", "price": 0.13 },
  { "name": "MONOPOLY PLUS", "price": 0.66 },
  { "name": "MXGP 2021 - The Official Motocross Videogame", "price": 2.59 },
  { "name": "MXGP 2021 - The Official Motocross Videogame - Xbox Series X|S", "price": 2.59 },
  { "name": "MY HERO ONE'S JUSTICE 2 Deluxe Edition", "price": 4.96 },
  { "name": "Madden NFL 19", "price": 24.11 },
  { "name": "Madden NFL 22 Xbox One", "price": 19.93 },
  { "name": "Madden NFL 22 Xbox Series X|S", "price": 23.2 },
  { "name": "Madden NFL 23 All Madden Edition Xbox One & Xbox Series X|S", "price": 15.9 },
  { "name": "Madden NFL 23 Xbox One", "price": 9.94 },
  { "name": "Madden NFL 23 Xbox One", "price": 26.51 },
  { "name": "Madden NFL 23 Xbox Series X|S", "price": 11.65 },
  { "name": "Madden NFL 23 Xbox Series X|S", "price": 31.07 },
  { "name": "Mafia: Definitive Edition", "price": 4.71 },
  { "name": "Mafia: Trilogy", "price": 7.83 },
  { "name": "Marble Duel", "price": 0.75 },
  { "name": "Marooners", "price": 0.26 },
  { "name": "Marvel's Midnight Suns Enhanced Edition", "price": 24.85 },
  { "name": "Marvel's Midnight Suns Legendary Edition", "price": 34.17 },
  { "name": "Masters of Anima", "price": 0.48 },
  { "name": "Mayhem Brawler", "price": 0.88 },
  { "name": "Maze Blaze", "price": 0.18 },
  { "name": "McPixel 3", "price": 1.95 },
  { "name": "Metal Wolf Chaos XD", "price": 0.93 },
  { "name": "Microsoft 365 Family", "price": 0.0 },
  { "name": "Microsoft 365 Personal", "price": 0.0 },
  { "name": "Miden Tower", "price": 0.55 },
  { "name": "Minemaze", "price": 0.08 },
  { "name": "Mini Madness", "price": 0.33 },
  { "name": "Minigolf Adventure", "price": 0.09 },
  { "name": "Mittelborg: City of Mages", "price": 0.14 },
  { "name": "Monster Energy Supercross - The Official Videogame 5", "price": 2.33 },
  { "name": "Monster Energy Supercross 5 - Special Edition", "price": 2.87 },
  { "name": "Monster Prom: XXL", "price": 0.39 },
  { "name": "Morkredd", "price": 0.37 },
  { "name": "MotoGP™22", "price": 2.59 },
  { "name": "Mount & Blade II: Bannerlord", "price": 10.19 },
  { "name": "Mount & Blade II: Bannerlord - Digital Companion", "price": 0.59 },
  { "name": "Mount & Blade II: Bannerlord Digital Deluxe Edition", "price": 3.11 },
  { "name": "Mount & Blade: Warband", "price": 0.26 },
  { "name": "Munchkin: Quacked Quest", "price": 0.74 },
  { "name": "My Friend Pedro", "price": 0.37 },
  { "name": "My Friend Pedro Win10", "price": 0.37 },
  { "name": "NARAKA: BLADEPOINT - Deluxe Edition", "price": 5.07 },
  { "name": "NARAKA: BLADEPOINT - Standard Edition", "price": 2.94 },
  { "name": "NARAKA: BLADEPOINT - Ultimate Edition", "price": 7.28 },
  { "name": "NARUTO SHIPPUDEN™: Ultimate Ninja® STORM 4", "price": 0.62 },
  { "name": "NARUTO SHIPPUDEN™: Ultimate Ninja® STORM Trilogy", "price": 1.03 },
  { "name": "NBA 2K23 Michael Jordan Edition", "price": 22.78 },
  { "name": "NBA 2K23 for Xbox One", "price": 9.06 },
  { "name": "NBA 2K23 for Xbox Series X|S", "price": 12.43 },
  { "name": "Necromunda: Underhive Wars", "price": 2.52 },
  { "name": "New Tales from the Borderlands", "price": 13.22 },
  { "name": "Ninja Shodown", "price": 0.15 },
  { "name": "Ninja Warrior Epic Quest", "price": 0.18 },
  { "name": "Nippon Marathon", "price": 0.28 },
  { "name": "Nobody Saves the World + Frozen Hearth Bundle", "price": 1.34 },
  { "name": "Noel the Mortal Fate", "price": 0.93 },
  { "name": "Not For Broadcast", "price": 6.48 },
  { "name": "Not for Broadcast Deluxe Edition", "price": 2.68 },
  { "name": "ONE PIECE BURNING BLOOD - Gold Edition", "price": 2.5 },
  { "name": "ONE PIECE World Seeker Deluxe Edition", "price": 2.7 },
  { "name": "ONE PIECE: PIRATE WARRIORS 4 Deluxe Edition", "price": 4.35 },
  { "name": "ONE PUNCH MAN: A HERO NOBODY KNOWS", "price": 2.38 },
  { "name": "Observation", "price": 0.46 },
  { "name": "Ogre: Console Edition", "price": 1.17 },
  { "name": "Old Man's Journey", "price": 0.26 },
  { "name": "Olija", "price": 0.44 },
  { "name": "Outbreak Platinum Collection", "price": 1.76 },
  { "name": "Outbreak Silver Collection", "price": 1.39 },
  { "name": "Outbuddies DX", "price": 0.27 },
  { "name": "Oxyjet", "price": 1.08 },
  { "name": "PGA TOUR 2K23", "price": 18.12 },
  { "name": "PGA TOUR 2K23 Cross-Gen Edition", "price": 20.71 },
  { "name": "PGA TOUR 2K23 Tiger Woods Edition", "price": 43.49 },
  { "name": "PGA TOUR 2K23 x NBA 2K23 Bundle", "price": 19.93 },
  { "name": "Pang Adventures", "price": 0.21 },
  { "name": "Party Hard 2", "price": 0.44 },
  { "name": "Pikuniku", "price": 0.24 },
  { "name": "Pit People", "price": 0.41 },
  { "name": "Pizza Tycoon", "price": 4.09 },
  { "name": "Plunder Panic", "price": 4.42 },
  { "name": "Pocket Witch", "price": 2.48 },
  { "name": "Poker Club", "price": 0.82 },
  { "name": "Police Stories", "price": 0.33 },
  { "name": "Power Rangers: Battle for the Grid", "price": 0.74 },
  { "name": "Power Rangers: Battle for the Grid - Digital Collector's Edition", "price": 1.11 },
  { "name": "Power Rangers: Battle for the Grid Super Edition", "price": 1.85 },
  { "name": "Prizma Puzzle Prime", "price": 0.33 },
  { "name": "Pro Gymnast Simulator + Brawl Chess", "price": 0.39 },
  { "name": "Project Snaqe", "price": 0.21 },
  { "name": "Pure Pool", "price": 0.18 },
  { "name": "Pushy and Pully in Blockland", "price": 0.37 },
  { "name": "REZ PLZ", "price": 0.22 },
  { "name": "RIDE 4", "price": 3.11 },
  { "name": "RIDE 4 - Special Edition", "price": 4.14 },
  { "name": "RISK", "price": 0.27 },
  { "name": "Rabbids®: Party of Legends", "price": 7.42 },
  { "name": "Record of Lodoss War-Deedlit in Wonder Labyrinth-", "price": 1.3 },
  { "name": "Red Dead Online", "price": 2.94 },
  { "name": "Red Dead Redemption 2", "price": 5.78 },
  { "name": "Return to Monkey Island", "price": 5.4 },
  { "name": "Riddled Corpses EX", "price": 0.1 },
  { "name": "Riders Republic Ultimate Edition", "price": 15.11 },
  { "name": "Riders Republic™", "price": 7.4 },
  { "name": "RiffTrax: The Game", "price": 0.37 },
  { "name": "Rise of Fox Hero", "price": 0.29 },
  { "name": "Riverbond", "price": 0.46 },
  { "name": "Road Redemption", "price": 0.41 },
  { "name": "Robo Revenge Squad", "price": 2.1 },
  { "name": "Robotry!", "price": 1.17 },
  { "name": "Rogue Star Rescue", "price": 3.21 },
  { "name": "Rubber Bandits", "price": 1.46 },
  { "name": "Ruiner", "price": 0.29 },
  { "name": "Ruinverse", "price": 0.55 },
  { "name": "Rusty Spout Rescue Adventure", "price": 0.26 },
  { "name": "SBK™22", "price": 4.14 },
  { "name": "SCARLET NEXUS", "price": 3.88 },
  { "name": "STAR WARS Jedi: Fallen Order™", "price": 6.62 },
  { "name": "STAR WARS Jedi: Fallen Order™ Deluxe Edition", "price": 8.85 },
  { "name": "SWORD ART ONLINE Alicization Lycoris", "price": 2.59 },
  { "name": "SWORD ART ONLINE: FATAL BULLET Complete Edition", "price": 2.39 },
  { "name": "Screencheat", "price": 0.19 },
  { "name": "Seeds of Resilience", "price": 0.1 },
  { "name": "Sekiro™: Shadows Die Twice - GOTY Edition", "price": 4.66 },
  { "name": "Serious Sam 4", "price": 0.89 },
  { "name": "Serious Sam Collection", "price": 1.11 },
  { "name": "Serious Sam: Siberian Mayhem", "price": 4.12 },
  { "name": "Shadow Warrior", "price": 0.34 },
  { "name": "Shadow Warrior 2", "price": 0.34 },
  { "name": "Shadow Warrior 3", "price": 5.81 },
  { "name": "Shady Part of Me", "price": 1.24 },
  { "name": "Shape of the World", "price": 0.28 },
  { "name": "Shenmue I & II", "price": 0.42 },
  { "name": "Shenmue I & II", "price": 0.65 },
  { "name": "Shikhondo - Soul Eater", "price": 0.25 },
  { "name": "Shing!", "price": 0.15 },
  { "name": "Shining Resonance Refrain", "price": 0.86 },
  { "name": "Shotgun Farmers", "price": 0.37 },
  { "name": "Sid Meier's Civilization VI", "price": 2.75 },
  { "name": "Sir Lovelot", "price": 0.15 },
  { "name": "Sisters Royale: Five Sisters Under Fire", "price": 0.52 },
  { "name": "Slipstream", "price": 0.86 },
  { "name": "Smart Moves 2", "price": 0.24 },
  { "name": "Smoots Golf", "price": 0.18 },
  { "name": "Smoots Summer Games", "price": 0.18 },
  { "name": "SnowRunner - 1-Anniversary Edition", "price": 9.54 },
  { "name": "Soul Hackers 2 - Digital Deluxe Edition", "price": 11.65 },
  { "name": "Space Engineers", "price": 0.74 },
  { "name": "Space Raiders in Space", "price": 0.44 },
  { "name": "Sparkle Bundle", "price": 0.66 },
  { "name": "Speed Brawl", "price": 0.52 },
  { "name": "Squid Hero for Kinect", "price": 0.13 },
  { "name": "Star Hunter DX", "price": 0.37 },
  { "name": "Stellar Interface", "price": 0.08 },
  { "name": "Streets of Rage 4", "price": 0.93 },
  { "name": "Streets of Rogue", "price": 0.37 },
  { "name": "Super Blood Hockey", "price": 0.22 },
  { "name": "Super Hydorah", "price": 1.65 },
  { "name": "Super Pixel Kid", "price": 0.08 },
  { "name": "Super Rebellion", "price": 0.22 },
  { "name": "Super Soccer Blast: America vs Europe", "price": 0.37 },
  { "name": "Super Sports Blast", "price": 0.93 },
  { "name": "Super Tennis Blast", "price": 0.55 },
  { "name": "Super Woden GP", "price": 0.62 },
  { "name": "Synchro Hedgehogs", "price": 0.24 },
  { "name": "TEKKEN 7", "price": 2.25 },
  { "name": "Tales of Arise", "price": 6.34 },
  { "name": "Tank Brawl 2: Armor Fury", "price": 0.37 },
  { "name": "Temple Dash: Jungle Adventure", "price": 0.08 },
  { "name": "Ten Dates", "price": 1.07 },
  { "name": "The Ascent", "price": 0.78 },
  { "name": "The Coma 2: Vicious Sisters", "price": 0.35 },
  { "name": "The Crew® 2 Special Edition", "price": 3.11 },
  { "name": "The Escapists: Supermax Edition", "price": 1.3 },
  { "name": "The FMV Bundle", "price": 1.9 },
  { "name": "The Jackbox Party Pack", "price": 0.52 },
  { "name": "The Jackbox Party Pack 5", "price": 0.93 },
  { "name": "The Jackbox Party Pack 7", "price": 1.33 },
  { "name": "The Jackbox Party Quadpack", "price": 2.91 },
  { "name": "The Last Door - Complete Edition", "price": 0.39 },
  { "name": "The Lord of the Rings: Adventure Card Game - Definitive Edition", "price": 0.74 },
  { "name": "The Messenger", "price": 0.59 },
  { "name": "The Metronomicon: Slay the Dance Floor", "price": 0.26 },
  { "name": "The Metronomicon: Slay the Dance Floor Deluxe Edition", "price": 0.46 },
  { "name": "The Oregon Trail", "price": 11.68 },
  { "name": "The Outer Worlds: Board-Approved Bundle", "price": 12.86 },
  { "name": "The Quarry - Deluxe Edition", "price": 20.71 },
  { "name": "The Quarry for Xbox One", "price": 15.53 },
  { "name": "The Quarry for Xbox Series X|S", "price": 18.12 },
  { "name": "The Redress of Mira", "price": 5.04 },
  { "name": "The Shadow Warrior Collection", "price": 3.64 },
  { "name": "The Surge", "price": 1.43 },
  { "name": "The Surge 2 - Windows 10", "price": 1.68 },
  { "name": "The Talos Principle", "price": 0.2 },
  { "name": "The Wild Eight", "price": 0.22 },
  { "name": "The Witcher 3: Wild Hunt", "price": 5.78 },
  { "name": "The Witcher 3: Wild Hunt – Complete Edition", "price": 10.25 },
  { "name": "Them's Fightin' Herds", "price": 0.88 },
  { "name": "Them's Fightin' Herds: Deluxe Edition", "price": 2.23 },
  { "name": "Think of the Children", "price": 0.35 },
  { "name": "Thronebreaker: The Witcher Tales", "price": 1.86 },
  { "name": "Ticket to Ride", "price": 0.59 },
  { "name": "Timothy vs the Aliens", "price": 0.51 },
  { "name": "Tiny Tina's Assault on Dragon Keep: A Wonderlands One-sho...", "price": 2.27 },
  { "name": "Tiny Tina's Wonderlands", "price": 15.5 },
  { "name": "Tiny Tina's Wonderlands: Chaotic Great Edition", "price": 16.93 },
  { "name": "Tiny Tina's Wonderlands: Next-Level Edition", "price": 18.52 },
  { "name": "Tom Clancy's Ghost Recon® Breakpoint Deluxe Edition", "price": 3.73 },
  { "name": "Tony Hawk's™ Pro Skater™ 1 + 2 - Cross-Gen Deluxe Bundle", "price": 4.66 },
  { "name": "Total Arcade Racing", "price": 0.22 },
  { "name": "Totally Reliable Delivery Service", "price": 0.28 },
  { "name": "Touchdown Pinball", "price": 0.19 },
  { "name": "Trailmakers", "price": 0.73 },
  { "name": "Train Station Renovation", "price": 0.59 },
  { "name": "Trash Sailors", "price": 0.88 },
  { "name": "Trek to Yomi", "price": 0.96 },
  { "name": "Trials Fusion", "price": 0.26 },
  { "name": "Tribal Pass", "price": 0.11 },
  { "name": "Tricky Towers", "price": 0.27 },
  { "name": "Trigger Witch", "price": 0.55 },
  { "name": "Trine 4: The Nightmare Prince", "price": 0.56 },
  { "name": "Tunche", "price": 0.74 },
  { "name": "Two Point Campus", "price": 8.13 },
  { "name": "UFC® 4", "price": 3.62 },
  { "name": "UFC® 4 Deluxe Edition", "price": 4.14 },
  { "name": "Unit 4: Couch Attack Bundle", "price": 0.7 },
  { "name": "Unrailed!", "price": 0.52 },
  { "name": "Unruly Heroes", "price": 0.51 },
  { "name": "Urban Flow", "price": 0.29 },
  { "name": "Valkyria Chronicles 4 Complete Edition", "price": 4.66 },
  { "name": "Vermintide - Digital Value Pack", "price": 2.07 },
  { "name": "Volley & Tennis Bundle Blast", "price": 0.59 },
  { "name": "WINGSPAN", "price": 0.74 },
  { "name": "WRC Collection FIA World Rally Championship", "price": 3.3 },
  { "name": "WWE 2K22 for Xbox One", "price": 7.77 },
  { "name": "WWE 2K22 for Xbox Series X|S", "price": 9.06 },
  { "name": "WWE 2K22 nWo 4-Life Edition", "price": 18.35 },
  { "name": "Wales Interactive Publisher Bundle", "price": 34.77 },
  { "name": "Wargroove", "price": 2.36 },
  { "name": "Warhammer 40,000: Shootas, Blood & Teef", "price": 3.72 },
  { "name": "Warp Drive", "price": 1.39 },
  { "name": "Watch Dogs®2 - Deluxe Edition", "price": 2.8 },
  { "name": "Watch Dogs®: Legion Ultimate Edition", "price": 7.25 },
  { "name": "We Are The Dwarves", "price": 0.29 },
  { "name": "Weird West", "price": 5.81 },
  { "name": "Windjammers 2", "price": 0.96 },
  { "name": "Woodle Tree 2: Deluxe+", "price": 0.15 },
  { "name": "X-Morph: Defense", "price": 0.21 },
  { "name": "X-Morph: Defense Complete Edition", "price": 0.31 },
  { "name": "XCOM® 2 Collection", "price": 1.68 },
  { "name": "Yakuza: Like a Dragon", "price": 3.57 },
  { "name": "Yakuza: Like a Dragon Legendary Hero Edition", "price": 5.28 },
  { "name": "You Suck At Parking + Parking Pass Season 2: Inferno", "price": 2.0 },
  { "name": "Young Souls", "price": 1.12 },
  { "name": "Yu-Gi-Oh! Legacy of the Duelist", "price": 0.26 },
  { "name": "Yu-Gi-Oh! Legacy of the Duelist : Link Evolution", "price": 2.37 }
]

function floor(price) {
  let enterPrice = Number(price)
  const lastNum = Number(enterPrice.toString().split('').pop())

  switch (lastNum) {
    case 1:
      enterPrice += 4
      break;
    case 2:
      enterPrice += 3
      break;
    case 3:
      enterPrice += 2
      break;
    case 4:
      enterPrice += 1
      break;
    case 6:
      enterPrice += 4
      break;
    case 7:
      enterPrice += 3
      break;
    case 8:
      enterPrice += 2
      break;
    case 9:
      enterPrice += 1
      break;
    default:
      enterPrice
      break;
  }
  return enterPrice;
}

function result() {
  const value = Number(input.value) + .1
  const res = value * usd
  const finishRes = res + resSwitсh(input.value)
  output.innerHTML = floor(finishRes.toFixed())
}

function resultFromList(price) {
  const value = Number(price) + .1
  const res = value * usd + 40
  const finishRes = res + resSwitсh(price)
  return floor(finishRes.toFixed())
}

function resSwitсh(value) {
  let a;
  if (value <= 1) {
    a = 40
  } else if (value > 1 && value <= 5) {
    a = 50
  } else if (value > 5 && value <= 10) {
    a = 70
  } else if (value > 10 && value <= 15) {
    a = 85
  } else if (value > 15 && value <= 20) {
    a = 100
  } else if (value > 20 && value <= 25) {
    a = 150
  } else if (value > 25) {
    a = 180
  }
  return a
}

input.oninput = result


arr.map((a) => {
  const item = document.createElement('li')
  let res = resultFromList(a.price)
  item.innerHTML = `${a.name}: ${res}`
  list.append(item)
})

function showMenu() {
  showBtn.classList.add('active')
  list.classList.add('active');
  showBtn.innerHTML = 'Скрыть Список'
  showBtn.style.background = 'red'

}

function hiddenMenu() {
  showBtn.classList.remove('active')
  list.classList.remove('active');
  showBtn.innerHTML = 'Показать Список'
  showBtn.style.background = 'greenyellow'
}
